---
settings:
  name: Keystone
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ko-kr,us-en,ja-jp,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Keystone 문서
    url: "/index.html"
  - title: 릴리스 정보
    entries:
    - title: Keystone STaaS의 새로운 기능
      url: "/release-notes/whats-new.html"
    - title: 해결된 문제
      url: "/release-notes/fixed-issues.html"
    - title: 알려진 문제
      url: "/release-notes/known-issues.html"
    - title: 알려진 제한 사항
      url: "/release-notes/known-limitations.html"
  - title: Keystone에 대해 자세히 알아보십시오
    entries:
    - title: 개요
      url: "/concepts/overview.html"
    - title: Keystone 인프라
      url: "/concepts/infra.html"
    - title: 구성 요소
      url: "/concepts/components.html"
    - title: 데이터 흐름
      url: "/concepts/data-flow.html"
    - title: 운영 모델
      url: "/concepts/operational-models.html"
    - title: Keystone 컬렉터
      url: "/installation/installation-overview.html"
  - title: Keystone 설정 및 구성
    entries:
    - title: 요구 사항
      entries:
      - title: VMware vSphere를 참조하십시오
        url: "/installation/vapp-prereqs.html"
      - title: 리눅스
        url: "/installation/linux-prereqs.html"
      - title: ONTAP and StorageGRID 를 참조하십시오
        url: "/installation/addl-req.html"
    - title: Keystone Collector를 설치합니다
      entries:
      - title: VMware vSphere에 구축
        url: "/installation/vapp-installation.html"
      - title: Linux에 설치합니다
        url: "/installation/linux-installation.html"
      - title: 무결성을 검증합니다
        url: "/installation/validation.html"
    - title: Keystone Collector 구성
      url: "/installation/configuration.html"
    - title: AutoSupport를 구성합니다
      url: "/installation/asup-config.html"
    - title: Keystone Collector 보안
      url: "/installation/security.html"
    - title: 대금 청구를 위해 수집된 데이터
      url: "/installation/data-collection.html"
  - title: 모니터링 및 업그레이드
    entries:
    - title: 시스템 상태를 모니터링합니다
      url: "/installation/monitor-health.html"
    - title: Keystone Collector 업그레이드
      url: "/installation/upgrade.html"
  - title: Keystone 대시보드
    entries:
    - title: Keystone 대시보드 보기
      url: "/integrations/keystone-aiq.html"
    - title: 사용 세부 정보를 보고 보고서를 생성합니다
      url: "/integrations/aiq-keystone-details.html"
    - title: 구독 탭을 클릭합니다
      url: "/integrations/subscriptions-tab.html"
    - title: 현재 소비 탭
      url: "/integrations/current-usage-tab.html"
    - title: 소비 경향 탭
      url: "/integrations/capacity-trend-tab.html"
    - title: 볼륨 및 개체 탭
      url: "/integrations/volumes-objects-tab.html"
    - title: 자산 탭
      url: "/integrations/assets-tab.html"
    - title: 성능 탭
      url: "/integrations/performance-tab.html"
    - title: BlueXP에서 Keystone 구독 관리
      url: "/integrations/keystone-cm.html"
  - title: Keystone STaaS 서비스
    entries:
    - title: 메트릭 및 정의
      url: "/concepts/metrics.html"
    - title: 서비스 품질
      url: "/concepts/qos.html"
    - title: 지원되는 스토리지
      url: "/concepts/supported-storage-services.html"
    - title: 지원되는 용량
      url: "/concepts/supported-storage-capacity.html"
    - title: 서비스 레벨
      url: "/concepts/service-levels.html"
    - title: 서비스 수준을 위해 지원되는 용량
      url: "/concepts/capacity-requirements.html"
    - title: Keystone 구독 서비스 버전 1
      url: "/subscription-services-v1.html"
    - title: 애드온 서비스
      entries:
      - title: 고급 데이터 보호
        url: "/concepts/adp.html"
      - title: 데이터 계층화
        url: "/concepts/data-tiering.html"
      - title: Equinix 지원 서비스
        url: "/concepts/equinix.html"
      - title: 반품 불가, 비휘발성 구성 요소 및 SnapLock 준수
        url: "/concepts/nrnvc.html"
      - title: 미국 시민 지원(USCS)
        url: "/concepts/uscs.html"
  - title: 청구
    entries:
    - title: Keystone 가격
      url: "/concepts/pricing.html"
    - title: 약정 용량에 따른 청구
      url: "/concepts/committed-capacity-billing.html"
    - title: 사용량 기반 측정
      url: "/concepts/consumed-capacity-billing.html"
    - title: 버스트 소비에 기초한 청구
      url: "/concepts/burst-consumption-billing.html"
    - title: 기타 볼륨 유형에 따른 청구
      url: "/concepts/misc-volume-billing.html"
    - title: 청구 일정
      url: "/concepts/billing-schedules.html"
  - title: NetApp 글로벌 서비스 지원 센터
    url: "/concepts/gssc.html"
  - title: 법적 고지
    url: "/legal-notices.html"
