---
sidebar: sidebar 
permalink: concepts/components.html 
keywords: infrastructure component, deployment requirement, installation requirement 
summary: 인프라 구성 요소 
---
= 배포용 구성 요소
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이 섹션에는 사용자 환경에서 NetApp Keystone STaaS 서비스를 지원하는 데 필요한 구성 요소가 나열되어 있습니다.



== 사이트 요구 사항

공간, 랙, PDU, 전력, 디스크, 디스크, 그리고 냉각, 여기에 설명된 추가 네트워크 및 보안 요구 사항.



=== 공간

Keystone 인프라 장비를 호스팅할 설치 공간(고객이 제공) NetApp은 최종 구성을 기준으로 중량 사양을 제공합니다.



=== 랙

고객이 운영하는 제품의 4개의 포스트 랙(고객이 제공) NetApp 운영 오퍼링의 요구사항에 따라 NetApp 또는 고객이 랙을 제공할 수 있습니다. NetApp은 42개의 세부 랙을 제공합니다.



=== PDU를 사용합니다

충분한 C13 콘센트가 있는 2개의 독립된 보호 회로에 연결된 PDU(Power Distribution Unit)를 제공해야 합니다. 고객 운영 서비스의 경우 경우에 따라 C19 아울렛이 필요합니다. NetApp에서 운영하는 오퍼링의 경우 요구사항에 따라 NetApp 또는 고객이 PDU를 제공할 수 있습니다.



=== 전원

필요한 전원을 제공해야 합니다. NetApp은 200V 등급(일반 A, 최대 A, 일반 W, 최대 W, 전원 코드 유형, 및 수량), 최종 구성 기준 모든 구성 요소에는 중복 전원 공급 장치가 있습니다. NetApp은 캐비닛 내 전원 코드를 제공합니다.



=== 냉각

NetApp은 최종 구성 및 요구사항에 따라 냉각 요구사항 사양(일반 BTU, 최대 BTU)을 제공할 수 있습니다.



=== 스토리지 가상 머신

Keystone 가입 모니터링 및 측정을 지원하려면 스토리지 가상 시스템(스토리지 VM)을 다음과 같이 구축해야 합니다. Keystone 수집기에 하나의 스토리지 VM이 필요하며, OpsRamp 게이트웨이에는 다른 스토리지 VM이 필요합니다

* Keystone Collector - 사용 메트릭 수집에 사용됨:
+
** vCPU: 4
** VRAM: 16GB
** vDisk: 200GB입니다


* OpsRamp Gateway – Keystone GSSC의 실시간 모니터 + 원격 지원 ONTAP에 사용:
+
** vCPU: 8
** VRAM: 16GB
** vDisk: 100GB






=== 구축 옵션

Keystone 수집기는 다음 방법을 통해 구축할 수 있습니다.

* VMware OVA 템플릿(VMware vCenter Server 6.7 이상이 필요함)
* 고객은 Red Hat Enterprise Linux 7 또는 8 또는 CentOS 7 Linux 서버를 제공하며 Keystone 소프트웨어는 '.rpm' 설치 프로세스를 통해 설치됩니다.


OpsRamp 게이트웨이는 다음 구성에 구축됩니다.

* VMware OVA 템플릿(VMware vCenter Server 6.7 이상이 필요함)
* 에 대한 부팅 가능한 .iso 설치 프로그램
+
** Citrix XenServer를 참조하십시오
** Microsoft Hyper-V를 참조하십시오
** 커널 기반 가상 머신(Linux KVM)






=== 네트워킹

Keystone Collector 및 OpsRamp Gateway의 운영 및 유지 관리를 위해 다음 서비스에 아웃바운드 액세스가 필요합니다.

* support.netapp.com (사용량 데이터 업로드)
* keystone.netapp.com (소프트웨어 업데이트)
* HUB.Docker.IO(소프트웨어 업데이트)


고객 요구 사항 및 사용하는 스토리지 컨트롤러에 따라 NetApp은 고객 사이트에서 10GB, 40GB, 100GB 연결을 제공할 수 있습니다.

NetApp은 NetApp에서 제공하는 인프라 장치에만 필요한 트랜시버를 제공합니다. 고객 장치에 필요한 트랜시버와 NetApp에서 제공하는 Keystone 인프라 장치에 케이블을 연결해야 합니다.



== 원격 액세스 요구 사항

고객 데이터 센터에 설치된 스토리지 인프라 또는 고객 소유의 코로케이션 서비스와 Keystone 운영 센터 간에 네트워크 연결이 필요합니다. 고객은 컴퓨팅 및 가상 시스템과 인터넷 서비스를 제공해야 합니다. 네트워크 설계는 보안 프로토콜을 통해 이루어져야 하며 방화벽 정책은 NetApp 및 고객 모두가 승인한 것입니다.

NetApp은 Keystone 고객에게 모니터링 및 청구 같은 서비스를 제공하기 위해 모니터링 및 관리를 위해 설치된 하드웨어 및 소프트웨어 구성요소에 액세스해야 합니다. 가장 일반적인 방법은 고객 네트워크에 대한 VPN(가상 사설망) 연결을 설정하고 필요한 데이터에 액세스하는 것입니다. 고객이 방화벽 포트를 열고 새로운 서비스로 인해 발생하는 운영상의 복잡성을 극복하기 위해 모니터링 도구는 외부 연결을 시작합니다. OpsRamp 및 Zuora와 같은 NetApp 클라우드 애플리케이션은 이 연결을 사용하여 해당 서비스를 수행합니다. 이 방법은 이 서비스의 일부인 모니터링 구성 요소에 대한 액세스를 제공하면서 방화벽 포트를 열지 않는 고객의 요구 사항을 충족합니다.
