---
sidebar: sidebar 
permalink: concepts/metrics.html 
keywords: metrics, GiB, IOPS, latency, durability, v3, version 3 
summary: NetApp Keystone STaaS 서비스는 여러 가지 용어를 사용하여 메트릭을 측정합니다. Keystone 서비스 버전 3을 사용할 경우 이러한 약관에 대해 자세히 알아보는 것이 좋습니다. 
---
= Keystone에 사용되는 메트릭 및 정의
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone STaaS 서비스는 여러 가지 용어를 사용하여 지표를 측정합니다. Keystone 사용하면서 이러한 용어에 대해 자세히 알아보는 것이 좋습니다.

Keystone STaaS 서비스 내에서 메트릭을 측정하기 위해 다음 용어와 정의가 사용됩니다.

* 용량: GiB, TiB, PiB로 측정됩니다.
* IOPS: 초당 처리되는 입출력 작업 수.
* 서비스 가용성
* 정확한 데이터 액세스에서의 내구성
* 지연 시간 및 속도




== 측정 지표

* *GiB, TiB, PiB 단위의 용량 측정*: 1024를 기준으로 데이터 저장 용량을 측정합니다(1GiB = 1024^3^바이트, 1TiB = 1024^4^바이트, 1PiB = 1024^5^바이트).
* *IOPS 단위의 작업 카운터 차트*: 애플리케이션에서 요청한 초당 프로토콜 작업 수입니다.
* * 가용성 *: 서비스에 의해 성공적으로 응답한 I/O 요청 수의 백분율로 측정되며, 서비스에 대한 총 I/O 요청 수로 나눈 값입니다. 이 값은 한 달 동안의 서비스 경계에서 측정되며, 고객이 제공한 시설, 네트워크 또는 기타 서비스의 예정된 서비스 중단 시간 또는 가용성 불량은 포함되지 않습니다.
* * 내구성 *: 고객 발생으로 인한 삭제 또는 손상을 제외하고 신뢰도 저하 없이 액세스되는 데이터의 비율입니다.
* * 지연 시간 *: 클라이언트로부터 수신된 I/O 요청을 서비스하는 시간, 서비스 경계(스토리지 컨트롤러 I/O 포트)에서 측정




=== 성능 메트릭

다음 성능 측정 항목은 통합 및 블록 최적화 서비스에 적용됩니다.

*통합 서비스:*

* *IOPS*: NFS를 탑재한 ONTAP 9.16.1의 경우, 각 성능 수준 인스턴스는 70% 읽기, 30% 쓰기 비율, 8KB 블록 크기, 1ms 대기 시간(표준의 경우 4ms)의 랜덤 액세스를 지원합니다.
* *처리량*: NFS를 탑재한 ONTAP 9.16.1의 경우, 각 성능 수준 인스턴스는 100% 읽기와 32KB 블록 크기의 순차적 액세스를 지원합니다.


*블록 최적화 서비스:*

* *IOPS*: FCP가 포함된 ONTAP 9.16.1의 경우, 각 성능 수준 인스턴스는 70% 읽기, 30% 쓰기 비율, 8KB 블록 크기, 1ms 지연 시간의 랜덤 액세스를 지원합니다.
* *처리량*: FCP가 포함된 ONTAP 9.16.1의 경우 각 성능 수준 인스턴스는 100% 읽기와 64KB 블록 크기의 순차적 액세스를 지원합니다.

