---
sidebar: sidebar 
permalink: concepts/metrics.html 
keywords: metrics, GiB, IOPS, latency, durability 
summary: Keystone 서비스의 메트릭 계산 및 정의 
---
= Keystone 서비스에 사용되는 메트릭 및 정의
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
지표 측정을 위해 Keystone(NetApp Keystone) STaaS 서비스 내에서 다음 용어 및 정의가 사용됩니다.

* 용량 측정 단위: GiB, TiB 및 PiB
* IO 밀도: IOPS/TiB: 워크로드에서 소비하는 총 공간(테비바이트)을 기준으로 초당 처리되는 입력/출력 작업의 수입니다.
* 서비스 가용성
* 정확한 데이터 액세스에서의 내구성
* 지연 시간 및 속도




== 측정 지표

* * gibibytes(GiB), tebytes(TiB) 및 pebibytes(PiB) *: 1024의 밑을 사용한 데이터 스토리지 용량 측정(1GiB = 1024^3^바이트, 1TiB = 1024^4^바이트, 1PiB = 1024^5^바이트).
* * IOPS/TiB에 포함된 운영 카운터 차트 *: 애플리케이션에서 요청하는 1초 당 프로토콜 작업을 워크로드에 사용되는 볼륨 크기로 나눕니다.
* * 가용성 *: 서비스에 의해 성공적으로 응답한 I/O 요청 수의 백분율로 측정되며, 서비스에 대한 총 I/O 요청 수로 나눈 값입니다. 이 값은 한 달 동안의 서비스 경계에서 측정되며, 고객이 제공한 시설, 네트워크 또는 기타 서비스의 예정된 서비스 중단 시간 또는 가용성 불량은 포함되지 않습니다.
* * 내구성 *: 고객 발생으로 인한 삭제 또는 손상을 제외하고 신뢰도 저하 없이 액세스되는 데이터의 비율입니다.
* * 지연 시간 *: 클라이언트로부터 수신된 I/O 요청을 서비스하는 시간, 서비스 경계(스토리지 컨트롤러 I/O 포트)에서 측정




=== 처리량 성능 메트릭

처리량 성능 메트릭은 다음에 기반하여 파일 및 블록 서비스에만 적용됩니다.

* 32KB 블록 크기
* 70% 읽기/30% 쓰기 I/O 혼합




=== 다양한 IO 밀도

IOPS/TiB 및/또는 MBps/TiB로 계산된 IO 밀도는 다음 요소에 따라 달라집니다.

* 워크로드 특성
* 지연 시간, 다음 제외:
+
** 애플리케이션 지연 시간
** 호스트 지연 시간
** 컨트롤러 포트와 데이터를 전송하는 동안 고객 네트워크의 지연 시간
** FabricPool의 경우 오브젝트 저장소로 데이터를 전송하는 데 따른 오버헤드 지연 시간입니다
** 지연 시간은 서비스 수준 최대 내에서 입출력을 유지하기 위해 QoS에서 자동으로 적용됩니다


* 사용된 용량의 일부로 계산되는 사용자 및 스냅샷 복사본 데이터입니다
* 볼륨에 있는 데이터의 양에 관계없이 각 ONTAP 볼륨에 할당된 절대 최소 IOPS:
+
** 익스트림: 1,000 IOPS
** Premium: 500 IOPS
** 성능, 표준 및 가치: 75 IOPS


* 고급 데이터 보호 추가 서비스를 사용하는 동안 대상 지연 시간은 로컬 스토리지의 입출력 요청을 처리하는 경우에만 적용됩니다.




=== 볼륨 AQoS

각 ONTAP 볼륨에는 적용 가능한 AQoS(적응형 서비스 품질) 정책이 적용되어 있어야 합니다. 그렇지 않으면 AQoS 정책이 적용되지 않은 각 볼륨 내의 용량은 최고 서비스 수준의 비율로 청구됩니다.
