---
sidebar: sidebar 
permalink: concepts/misc-volume-billing.html 
keywords: Keystone billing, special volume types, cloned volumes, SnapMirror destinations, LUNs, temporary volumes 
summary: Keystone 요금 청구 규칙은 특정 볼륨 구성에 따라 다릅니다. 이 페이지에서는 복제된 볼륨, SnapMirror 대상, LUN, 임시 볼륨 및 시스템 볼륨에 대한 요금 청구 방식을 설명합니다. 
---
= 특정 볼륨 유형에 대한 Keystone 청구
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone 요금 청구 규칙은 특정 볼륨 구성에 따라 다릅니다. 이러한 예외 사항을 알아두면 복제 볼륨, SnapMirror 대상, LUN 또는 임시 스토리지를 사용할 때 예상치 못한 요금이 발생하는 것을 방지할 수 있습니다.

다음 표는 각 볼륨 유형에 대한 청구 규칙을 요약한 것입니다.

[cols="1,2"]
|===
| 볼륨 유형 | 청구 규칙 


| 복제된 볼륨 | 표준 볼륨으로 청구됨 


| 임시 볼륨 | 청구되지 않음 


| SnapMirror 대상 | 목적지 성능 서비스 수준에 따라 청구됩니다. 


| LUN | 포함하는 볼륨의 성능 서비스 수준에 따라 요금이 청구됩니다. 


| 시스템 및 루트 볼륨 | 모니터링되지만 청구되지 않음 
|===


== 복제된 볼륨에 대한 청구

복제된 볼륨은 복제된 원본 볼륨과 동일한 성능 서비스 수준으로 표준 볼륨으로 청구됩니다. 모든 복제된 볼륨은 크기나 용도에 관계없이 측정되고 청구됩니다.



== 임시 볼륨에 대한 청구

볼륨을 이동할 때 임시(TMP) 볼륨이 ONTAP에 의해 생성되는 경우가 있습니다. 이러한 임시 볼륨은 수명이 짧으며 이러한 볼륨의 소비량은 청구 대상으로 측정되지 않습니다.



== SnapMirror 대상에 대한 청구

SnapMirror 대상 볼륨의 가격은 재해 복구 또는 장기 보존에 사용 여부와 관계없이 대상 볼륨에 할당된 성능 서비스 수준에 따라 결정됩니다. 데이터 보호에는 추가 요금이 없습니다.



== LUN에 대한 청구

LUN의 경우 요금은 볼륨의 성능 서비스 수준을 기준으로 청구됩니다.



== 시스템 및 루트 볼륨

시스템과 루트 볼륨은 Keystone 서비스의 전체 모니터링의 일부로 모니터링되지만 계산되거나 청구되지는 않습니다. 이러한 볼륨에 대한 소비는 청구 대상에서 제외됩니다.
