---
sidebar: sidebar 
permalink: concepts/misc-volume-billing.html 
keywords: Billing and miscellaneous scenarios 
summary: 기타 볼륨 유형에 따른 청구 
---
= Keystone 청구를 위한 기타 시나리오
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/




== 복제된 볼륨에 대한 청구

ONTAP에서 볼륨을 클로닝하고 이를 사용하여 데이터를 백업 및 복원하는 경우 추가 비용 없이 클론을 계속 사용할 수 있습니다. 그러나 광범위한 기간 동안 비즈니스의 다른 목적으로 사용된 복제된 볼륨은 청구됩니다.

다음 사항에 유의하십시오.

* 클론 볼륨의 크기가 상위 볼륨의 10% 미만이면(상위 볼륨에 사용된 물리적 용량과 비교하여 클론 볼륨에 사용된 물리적 용량) 충전이 무료입니다.
* 클론된 볼륨에 대해 24시간 유예 기간이 없으며 클론의 크기만 고려됩니다.
* 클론 볼륨이 상위 물리적 크기의 10%를 초과하면 클론이 표준 볼륨(논리적 사용된 용량)으로 청구됩니다.




== 고급 데이터 보호에 대한 청구

고급 데이터 보호 기능은 NetApp MetroCluster를 사용하여 물리적으로 분리된 두 클러스터 간에 데이터를 미러링합니다. MetroCluster 미러링된 애그리게이트의 경우 각 클러스터에 데이터가 두 번 기록됩니다. Keystone 서비스는 각 측면에서 독립적으로 소비에 청구되므로 두 개의 동일한 소비 레코드가 생성됩니다. 추가 비용은 데이터가 소스에 있는지, 미러링 또는 미러링되지 않은 데이터인지에 관계없이 구독의 모든 용량에 적용됩니다.

ONTAP 시스템 관리자(System Manager) 또는 Active IQ Unified Manager(Unified Manager)를 통해 클러스터를 모니터링하는 경우 이러한 툴과 Keystone에 보고된 소비 사이에 차이가 있을 수 있습니다. System Manager 및 Unified Manager는 미러링된(원격) 클러스터에 볼륨을 보고하지 않으며, Keystone 서비스가 보고하는 소비 메트릭의 절반만 보고합니다.

.예:
사이트 A와 사이트 B는 MetroCluster 구성으로 설정됩니다. 사용자가 사이트 A에서 10TB의 볼륨을 생성하면 사이트 B에서 동일한 10TB의 볼륨이 생성됩니다 Keystone은 각 사이트에서 10TB의 소비를 식별하여 20TB를 총 늘립니다. System Manager와 Unified Manager에서 사이트 A에 10TB 볼륨이 생성되었다고 보고하지만 사이트 B에 10TB 볼륨을 보고하지 않습니다

또한, 고급 데이터 보호 기능을 갖춘 Keystone 시스템에서 생성된 모든 볼륨은 해당 볼륨의 미러링 여부와 관계없이 고급 데이터 보호 사용에 포함됩니다.



== 임시 볼륨에 대한 청구

볼륨을 이동할 때 임시(TMP) 볼륨이 ONTAP에 의해 생성되는 경우가 있습니다. 이러한 임시 볼륨은 수명이 짧으며 이러한 볼륨의 소비량은 청구 대상으로 측정되지 않습니다.



== 청구 및 적응형 QoS 정책

Keystone은 서비스 수준에 따라 소비를 측정합니다. 각 서비스 수준은 특정 적응형 서비스 품질(QoS) 정책과 연계됩니다. 구축하는 동안 구독한 Keystone 서비스에 대한 각 QoS 정책에 대한 세부 정보가 제공됩니다. 스토리지 관리 작업 중에 예상치 못한 청구가 발생하지 않도록 서비스에 가입한 서비스 수준에 따라 볼륨에 적절한 QoS 정책이 할당되었는지 확인합니다. ONTAP의 QoS 정책에 대한 자세한 내용은 을 참조하십시오 link:https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html["QoS 개요를 통해 처리량 보장"^].



== SnapMirror 대상에 대한 청구

SnapMirror 대상 볼륨의 가격은 소스에 할당된 서비스 수준에 대한 QoS 정책의 적용을 받습니다. 하지만 소스에 연결된 QoS 정책이 없는 경우 사용 가능한 최저 서비스 수준을 기준으로 대상에 비용이 청구됩니다.



== LUN에 대한 청구

LUN의 경우 QoS 정책이 적용되는 볼륨과 동일한 청구 패턴이 이어집니다. LUN에 별도의 QoS 정책이 설정된 경우 다음을 수행합니다.

* LUN의 크기는 해당 LUN의 연결된 서비스 수준에 따라 소비용으로 계산됩니다.
* 볼륨에 설정된 서비스 수준의 QoS 정책에 따라 볼륨의 나머지 공간이 청구되는 경우




== 시스템 및 루트 볼륨

시스템과 루트 볼륨은 Keystone 서비스의 전체 모니터링의 일부로 모니터링되지만 계산되거나 청구되지는 않습니다. 이러한 볼륨에 대한 소비는 청구 대상에서 제외됩니다.
