---
sidebar: sidebar 
permalink: concepts/misc-volume-billing-v2.html 
keywords: Billing and miscellaneous scenarios 
summary: 클론 복제된 볼륨, 고급 데이터 보호 등을 포함한 특정 구성을 위한 Keystone 빌링에 대해 알아보십시오. 
---
= Keystone 청구를 위한 기타 시나리오
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
버전 2(v2)의 특정 구성에 대한 Keystone 요금 청구 방식을 이해하면 서비스 사용량을 최적화하고 비용을 관리하는 데 도움이 될 수 있습니다. 해당 구성에는 복제된 볼륨, 고급 데이터 보호, 임시 볼륨, QoS 정책, SnapMirror 대상, LUN, 시스템/루트 볼륨이 포함됩니다.



== 복제된 볼륨에 대한 청구

ONTAP에서 볼륨을 클로닝하고 이를 사용하여 데이터를 백업 및 복원하는 경우 추가 비용 없이 클론을 계속 사용할 수 있습니다. 그러나 광범위한 기간 동안 비즈니스의 다른 목적으로 사용된 복제된 볼륨은 청구됩니다.

다음 사항에 유의하십시오.

* 클론 볼륨의 크기가 상위 볼륨의 10% 미만이면(상위 볼륨에 사용된 물리적 용량과 비교하여 클론 볼륨에 사용된 물리적 용량) 충전이 무료입니다.
* 복제된 볼륨에는 24시간 유예 기간이 없습니다. 복제본의 크기만 고려됩니다.
* 클론 볼륨이 상위 물리적 크기의 10%를 초과하면 클론이 표준 볼륨(논리적 사용된 용량)으로 청구됩니다.




== 고급 데이터 보호를 위한 청구

고급 데이터 보호는 NetApp MetroCluster을 사용하여 물리적으로 분리된 두 클러스터 간에 데이터를 미러링합니다. MetroCluster 미러링된 애그리게이트의 경우 각 클러스터에 데이터가 두 번 기록됩니다. Keystone 서비스는 각 측면에서 독립적으로 소비에 청구되므로 두 개의 동일한 소비 레코드가 생성됩니다. 추가 비용은 데이터가 소스에 있는지, 미러링 또는 미러링되지 않은 데이터인지에 관계없이 구독의 모든 용량에 적용됩니다.

ONTAP 시스템 관리자(System Manager) 또는 Active IQ Unified Manager(Unified Manager)를 통해 클러스터를 모니터링하는 경우 이러한 툴과 Keystone에 보고된 소비 사이에 차이가 있을 수 있습니다. System Manager 및 Unified Manager는 미러링된(원격) 클러스터에 볼륨을 보고하지 않으며, Keystone 서비스가 보고하는 소비 메트릭의 절반만 보고합니다.

.예:
사이트 A와 사이트 B는 MetroCluster 구성으로 설정됩니다. 사용자가 사이트 A에서 10TB의 볼륨을 생성하면 사이트 B에서 동일한 10TB의 볼륨이 생성됩니다 Keystone은 각 사이트에서 10TB의 소비를 식별하여 20TB를 총 늘립니다. System Manager와 Unified Manager에서 사이트 A에 10TB 볼륨이 생성되었다고 보고하지만 사이트 B에 10TB 볼륨을 보고하지 않습니다

또한 고급 데이터 보호 기능을 갖춘 Keystone 시스템에서 생성된 모든 볼륨은 미러링되는지 여부와 관계없이 고급 데이터 보호의 사용 시 계산됩니다.



== 임시 볼륨에 대한 청구

볼륨을 이동할 때 임시(TMP) 볼륨이 ONTAP에 의해 생성되는 경우가 있습니다. 이러한 임시 볼륨은 수명이 짧으며 이러한 볼륨의 소비량은 청구 대상으로 측정되지 않습니다.



== 청구 및 적응형 QoS 정책

Keystone은 서비스 수준을 기준으로 소비를 측정합니다. 각 서비스 수준은 특정 적응형 서비스 품질(QoS) 정책과 연계됩니다. 구축 중에 구독한 Keystone 서비스의 각 적응형 QoS 정책에 대한 세부 정보를 통보받게 됩니다. 스토리지 관리 작업 중에 볼륨에 가입된 서비스 수준에 따라 적합한 적응형 QoS 정책이 할당되어 있는지 확인하여 예기치 않은 청구가 발생하지 않도록 하십시오. ONTAP의 적응형 QoS 정책에 대한 자세한 내용은 를 참조하십시오link:https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html["QoS 개요를 통해 처리량 보장"^].



== SnapMirror 대상에 대한 청구

SnapMirror 타겟 볼륨의 가격은 소스에 할당된 서비스 수준에 대한 적응형 QoS 정책이 적용됩니다. 그러나 소스에 연결된 적응형 QoS 정책이 없는 경우 사용 가능한 최저 서비스 수준을 기준으로 대상이 청구됩니다.



== LUN에 대한 청구

LUN의 경우 적응형 QoS 정책에 따라 관리되는 볼륨의 청구 패턴이 동일합니다. LUN에 별도의 적응형 QoS 정책을 설정한 경우:

* LUN의 크기는 해당 LUN의 연결된 서비스 수준에 따라 소비용으로 계산됩니다.
* 볼륨의 나머지 공간이 있는 경우, 볼륨에 설정된 서비스 수준의 적응형 QoS 정책에 따라 비용이 청구됩니다.




== 시스템 및 루트 볼륨

시스템과 루트 볼륨은 Keystone 서비스의 전체 모니터링의 일부로 모니터링되지만 계산되거나 청구되지는 않습니다. 이러한 볼륨에 대한 소비는 청구 대상에서 제외됩니다.
