---
sidebar: sidebar 
permalink: concepts/misc-volume-billing.html 
keywords: Billing and miscellaneous scenarios 
summary: 클론 복제된 볼륨, 고급 데이터 보호 등을 포함한 특정 구성을 위한 Keystone 빌링에 대해 알아보십시오. 
---
= Keystone 청구를 위한 기타 시나리오
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
버전 3(v3)의 특정 구성에 대한 Keystone 청구를 이해하면 서비스 사용을 최적화하고 비용을 관리하는 데 도움이 될 수 있습니다.  구성에는 복제된 볼륨, 임시 볼륨, SnapMirror 대상, LUN 및 시스템/루트 볼륨이 포함됩니다.



== 복제된 볼륨에 대한 청구

ONTAP에서 볼륨을 클로닝하고 이를 사용하여 데이터를 백업 및 복원하는 경우 추가 비용 없이 클론을 계속 사용할 수 있습니다. 그러나 광범위한 기간 동안 비즈니스의 다른 목적으로 사용된 복제된 볼륨은 청구됩니다.

다음 사항에 유의하십시오.

* 클론 볼륨의 크기가 상위 볼륨의 10% 미만이면(상위 볼륨에 사용된 물리적 용량과 비교하여 클론 볼륨에 사용된 물리적 용량) 충전이 무료입니다.
* 복제된 볼륨에는 24시간 유예 기간이 없습니다. 복제본의 크기만 고려됩니다.
* 클론 볼륨이 상위 물리적 크기의 10%를 초과하면 클론이 표준 볼륨(논리적 사용된 용량)으로 청구됩니다.




== 임시 볼륨에 대한 청구

볼륨을 이동할 때 임시(TMP) 볼륨이 ONTAP에 의해 생성되는 경우가 있습니다. 이러한 임시 볼륨은 수명이 짧으며 이러한 볼륨의 소비량은 청구 대상으로 측정되지 않습니다.



== SnapMirror 대상에 대한 청구

SnapMirror 대상 볼륨의 가격은 재해 복구 또는 장기 보존에 사용 여부와 관계없이 대상 볼륨에 할당된 성능 서비스 수준에 따라 결정됩니다. 데이터 보호에는 추가 요금이 없습니다.



== LUN에 대한 청구

LUN의 경우 요금은 볼륨의 성능 서비스 수준을 기준으로 청구됩니다.



== 시스템 및 루트 볼륨

시스템과 루트 볼륨은 Keystone 서비스의 전체 모니터링의 일부로 모니터링되지만 계산되거나 청구되지는 않습니다. 이러한 볼륨에 대한 소비는 청구 대상에서 제외됩니다.



== SnapMirror 대상에 대한 청구

SnapMirror 타겟 볼륨의 가격은 소스에 할당된 서비스 수준에 대한 적응형 QoS 정책이 적용됩니다. 그러나 소스에 연결된 적응형 QoS 정책이 없는 경우 사용 가능한 최저 서비스 수준을 기준으로 대상이 청구됩니다.



== LUN에 대한 청구

LUN의 경우 적응형 QoS 정책에 따라 관리되는 볼륨의 청구 패턴이 동일합니다. LUN에 별도의 적응형 QoS 정책을 설정한 경우:

* LUN의 크기는 해당 LUN의 연결된 서비스 수준에 따라 소비용으로 계산됩니다.
* 볼륨의 나머지 공간이 있는 경우, 볼륨에 설정된 서비스 수준의 적응형 QoS 정책에 따라 비용이 청구됩니다.




== 시스템 및 루트 볼륨

시스템과 루트 볼륨은 Keystone 서비스의 전체 모니터링의 일부로 모니터링되지만 계산되거나 청구되지는 않습니다. 이러한 볼륨에 대한 소비는 청구 대상에서 제외됩니다.
