---
sidebar: sidebar 
permalink: concepts/nrnvc.html 
keywords: Non-returnable, non-volatile components, SnapLock compliance, add-on service 
summary: NetApp은 NetApp Keystone 구독의 일환으로 파일, 블록 및 오브젝트 서비스에 대한 NRNVC 오퍼링을 확장합니다. 
---
= Keystone) 용 반환 불가, 비휘발성 부품 및 SnapLock) 규정 준수 추가 서비스
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone 구독의 일환으로 NetApp은 파일, 블록 및 오브젝트 서비스에 대한 반품 불가 비휘발성 구성 요소(NRNVC) 오퍼링을 확장합니다.

NetApp은 서비스 제공 시 사용된 모든 물리적 자산을 복구하지 않습니다. 단, NetApp이 서비스 제공 기간에 사용한 전체 물리적 자산을 복구하지 않습니다.

Keystone 구독의 일부로 이 애드온 서비스를 구독할 수 있습니다. 이 서비스를 구입한 경우 다음 사항에 유의하십시오.

* 서비스 기간 종료 시, 또는 서비스 기간 동안 드라이브 및 비휘발성 메모리의 반환이 실패하거나 결함이 발견된 경우에는 반환할 필요가 없습니다.
* 그러나 드라이브 및/또는 비휘발성 메모리에 대한 폐기 인증서를 작성해야 하며 다른 용도로는 사용할 수 없습니다.
* NRNVC와 관련된 추가 비용은 총 구독 서비스(표준 서비스, 고급 데이터 보호 및 데이터 계층화 포함) 월별 요금의 비율로 부과됩니다.
* 이 서비스는 파일, 블록 및 오브젝트 서비스에만 적용됩니다.


표준 및 클라우드 서비스에 대한 자세한 내용은 을 link:supported-storage-services.html["Keystone STaaS 서비스"]참조하십시오.

성과 서비스 수준에 대한 정보는 다음을 참조하세요. link:../concepts/service-levels.html["키스톤의 성과 서비스 수준"] .



== SnapLock 규정 준수

SnapLock 기술은 볼륨에 설정된 만료 날짜 이후에 드라이브를 사용할 수 없도록 하여 NRNVC 기능을 활성화합니다. 볼륨에 SnapLock 기술을 사용하려면 NRNVC를 구독해야 합니다. 이는 파일 및 블록 서비스에만 적용됩니다.

SnapLock 기술에 대한 자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/ontap/snaplock/snaplock-concept.html["SnapLock란"^].
