---
sidebar: sidebar 
permalink: concepts/pricing.html 
keywords: pricing, billing introduction, Keystone billing 
summary: Keystone은 유연하고 확장 가능한 소비 요구사항에 부합하는 용량제 모델을 제공합니다. 
---
= Keystone 가격
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone STaaS 종량제 구독 서비스는 스토리지 요구 사항에 맞춰 예측 가능하고 사전 가격이 책정되어 유연하고 확장 가능한 소비를 제공합니다.

Keystone 에서는 다음과 같은 청구 서비스를 제공합니다.

* 다양한 작업 부하 요구 사항을 충족하기 위해 IOPS 및 지연 시간을 기준으로 요금을 지불할 수 있습니다. Extreme, Premium, Standard, Value, Object, Cloud Volumes ONTAP 등 다양한 성능 서비스 계층을 통해 구매한 성능 서비스 수준에 따라 스토리지를 관리할 수 있습니다.
* 약정 용량에 대한 예측 가능한 청구와 가변(버스트) 용량 사용량에 대한 종량제 비용을 표시합니다.
* 하드웨어, 코어 OS의 번들 가격을 선택하고 $/TiB 단일 가격을 지원할 수 있습니다. 통합, 블록, 최적화, 객체 또는 클라우드 스토리지 서비스 등 각 스토리지 유형별로 단일 송장이 있습니다.
* 월별, 분기별, 반기별 또는 연간 등 서비스와 지불 옵션에 대한 유연한 기간을 선택할 수 있습니다.


Keystone 청구는 확정된 용량 및 가변 버스트 소비를 기반으로 합니다.

Keystone에서 지원되는 다양한 기능에 대한 자세한 내용은 을 참조하십시오 link:../concepts/supported-storage-capacity.html["Keystone에서 지원되는 스토리지 용량"].

* 관련 정보 *

* link:../concepts/committed-capacity-billing.html["약정 용량에 따른 청구"]
* link:../concepts/consumed-capacity-billing.html["사용량 기반 측정"]
* link:../concepts/burst-consumption-billing.html["버스트 소비에 기초한 청구"]
* link:../concepts/misc-volume-billing.html["기타 볼륨 유형에 따른 청구"]
* link:../concepts/billing-schedules.html["청구 일정"]

