---
sidebar: sidebar 
permalink: concepts/service-levels.html 
keywords: service levels, service level, rate plan or service level 
summary: Keystone STaaS 버전 3은 사전 정의된 서비스 수준에서 스토리지 용량을 제공합니다. Keystone에서 관리하는 각 볼륨은 서비스 수준과 연결됩니다. 
---
= 키스톤의 성능 서비스 수준
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
버전 3(v3)용 Keystone STaaS는 사전 정의된 성능 서비스 수준에서 데이터 저장 용량을 제공합니다. Keystone 서비스에서 관리하는 각 볼륨은 성능 서비스 수준과 연관됩니다.

구독에는 여러 요금제가 있을 수 있으며, 각 요금제는 성능 서비스 수준에 해당합니다. 각 요금제는 성능 서비스 수준별로 약정된 용량을 갖습니다.

성능 서비스 수준은 여러 인스턴스를 가질 수 있으며, 각 인스턴스는 고객 환경에서 해당 성능 서비스 수준에 할당된 별도의 스토리지 어레이를 나타냅니다. 각 성능 서비스 수준은 초당 입출력 작업 수(IOPS), 처리량(GBps), 지연 시간(ms)으로 정의되며, 이러한 지표는 성능 서비스 수준 인스턴스별로 측정 및 적용됩니다.

스토리지 환경, 스토리지 및 소비 요구 사항에 따라 성능 서비스 수준을 선택합니다. 기본 성능 서비스 수준은 기본적으로 제공됩니다. 추가 서비스를 선택한 경우 구체적인 성과 서비스 수준도 추가로 이용할 수 있습니다.


TIP: NetApp Keystone STaaS 성능 서비스 수준에 대한 자세한 서비스 설명을 사용할 수 있습니다.  https://www.netapp.com/services/keystone/terms-and-conditions/["여기"^] .

지원되는 스토리지 유형, 통합, 블록 최적화, 개체 및 클라우드 서비스에 대한 기본 성능 서비스 수준은 다음 섹션에 설명되어 있습니다.



== 통합 스토리지의 성능 서비스 수준

*지원 프로토콜*: FC, iSCSI, NFS, NFSv4/RDMA, NVMe/FC, NVMe/TCP, SMB, S3

|===


| *성능 서비스 수준* (성능 서비스 수준 인스턴스당 모든 사양) | * 익스트림 * | * 프리미엄 * | * 표준 * | * 값 * 


| * 샘플 워크로드 유형 * | AI/ML, HPC, InMem DB | 분석, EDA, OLTP | OLAP, IoT, 컨테이너 | 백업, 아카이브 


| *최대 IOPS*^1^ | 1M를 참조하십시오 | 550K | 500K | 해당 없음 


| *최대 GBps* | 40 | 20 | 20 | 해당 없음 


| * 목표 90 백분위수 대기 시간 * | <=1밀리초 | <=1밀리초 | <=4ms | >4밀리초 


| * 커밋된 최소 용량 * | 50티비 | 50티비 | 100TiB | 100TiB 


| *증분적 약정 용량 증가* 4+| 25TiB를 참조하십시오 


| * 약정 및 용량제 용량 유형 * 4+| 논리적 또는 물리적 
|===


== 블록 최적화 스토리지의 성능 서비스 수준

*지원 프로토콜*: NVMe/TCP, NVMe/FC, FC, iSCSI

|===


| *성능 서비스 수준* (성능 서비스 수준 인스턴스당 모든 사양) | * 익스트림 * | * 프리미엄 * 


| * 샘플 워크로드 유형 * 2+| SAP HANA, Oracle, MS SQL Server, EPIC 


| *최대 IOPS*^1^ | 850K | 450K 


| *최대 GBps* | 65 | 25 


| * 목표 90 백분위수 대기 시간 * | <=1밀리초 | <=1밀리초 


| * 커밋된 최소 용량 * | 50티비 | 50티비 


| *증분적 약정 용량 증가* 2+| 25TiB를 참조하십시오 


| * 약정 및 용량제 용량 유형 * 2+| 논리적 또는 물리적 
|===

NOTE: ^1^상호 배타적인 대상입니다. 실제 성능은 운영 체제 버전, 하드웨어, 워크로드 유형, 동시 작업 수 등 다양한 요인에 따라 달라질 수 있습니다.



=== 통합 및 블록 최적화 스토리지의 성능 서비스 수준에 대한 자세한 내용

기본 성능 서비스 수준 측정항목은 다음 조건에 따라 달라집니다.

* 성능 서비스 수준은 ONTAP 9.8 이상을 지원합니다.
* 통합 스토리지의 경우
+
** *IOPS*: NFS를 탑재한 ONTAP 9.16.1의 경우, 각 성능 수준 인스턴스는 70% 읽기, 30% 쓰기 비율, 8KB 블록 크기, 1ms 대기 시간(표준의 경우 4ms)의 랜덤 액세스를 지원합니다.
** *처리량*: NFS를 탑재한 ONTAP 9.16.1의 경우, 각 성능 수준 인스턴스는 100% 읽기와 32KB 블록 크기의 순차적 액세스를 지원합니다.


* 블록 최적화된 스토리지의 경우
+
** *IOPS*: FCP가 포함된 ONTAP 9.16.1의 경우, 각 성능 수준 인스턴스는 70% 읽기, 30% 쓰기 비율, 8KB 블록 크기, 1ms 지연 시간의 랜덤 액세스를 지원합니다.
** *처리량*: FCP가 포함된 ONTAP 9.16.1의 경우 각 성능 수준 인스턴스는 100% 읽기와 64KB 블록 크기의 순차적 액세스를 지원합니다.


* 지연 시간은 다음 사항을 포함하지 않습니다.
+
** 애플리케이션 또는 호스트 지연 시간
** 컨트롤러 포트 간 또는 컨트롤러 포트로 전송되는 고객의 네트워크 지연 시간
** FabricPool의 경우 데이터 전송과 관련된 오버헤드를 오브젝트 저장소로 이동합니다


* 지연 시간 값은 MetroCluster 쓰기 작업에 적용할 수 없습니다. 이러한 쓰기 작업은 원격 시스템의 거리에 따라 달라집니다.
* _expected IOPS_는 계층화 정책이 "없음"으로 설정되고 클라우드에 블록이 없는 경우에만 FabricPool를 대상으로 합니다. _expected IOPS_는 SnapMirror 동기식 관계가 아닌 볼륨을 대상으로 합니다.




== 객체 스토리지의 성능 서비스 수준

* 지원되는 프로토콜 *: S3

|===


| *성능 서비스 수준* | * 표준 * | * 값 * 


| *주문당 최소 약정 용량* | 200TiB | 500 티비 


| *증분적 약정 용량 증가* | 25티비 | 100TiB 


| * 약정 및 용량제 용량 유형 * 2+| 물리적 
|===


== 클라우드 스토리지

*지원되는 프로토콜*: NFS, CIFS, iSCSI 및 S3(AWS 및 Azure만 해당)

|===


| *성능 서비스 수준* | Cloud Volumes ONTAP 


| *주문당 최소 약정 용량* | 4TiB 


| *증분적 약정 용량 증가* | 1TiB 


| * 약정 및 용량제 용량 유형 * | 논리적 
|===
[NOTE]
====
* 컴퓨팅, 스토리지, 네트워킹과 같은 클라우드 네이티브 서비스는 클라우드 공급자가 송장을 발행합니다.
* 이러한 서비스는 클라우드 스토리지 및 컴퓨팅 특성에 따라 다릅니다.


====
* 관련 정보 *

* link:../concepts/supported-storage-capacity.html["지원되는 스토리지 용량입니다"]
* link:..//concepts/metrics.html["Keystone 서비스에 사용되는 메트릭 및 정의"]
* link:../concepts/pricing.html["Keystone 가격"]

