---
sidebar: sidebar 
permalink: concepts/sla-ransomware-v2.html 
keywords: ransomware, recovery, guarantee, SLA, Keystone, assurance 
summary: NetApp은 랜섬웨어 복구 보증 프로그램을 통해 랜섬웨어 공격이 발생할 경우 SnapLock Compliance 볼륨의 스냅샷 데이터 복구를 보장합니다 
---
= 랜섬웨어 복구 보장
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp은 랜섬웨어 복구 보증 프로그램을 통해 랜섬웨어 공격이 발생할 경우 SnapLock Compliance 볼륨의 스냅샷 데이터 복구를 보장합니다. NetApp 랜섬웨어 복구 보증 서비스는 랜섬웨어 복구 보증 프로그램을 지원하려면 필요하며, 관련 Keystone 주문과 별도로 구매해야 합니다.



== 서비스 레벨

해당 구독 기간 동안 Keystone 구독을 지원하는 모든 하드웨어에 랜섬웨어 복구 보증 서비스가 필요합니다.



== 서비스 크레딧


NOTE: SLA 및 보장은 후보 지명을 통해 제공됩니다.

모범 사례에 따라 SnapLock Compliance가 구축되고 NetApp 프로페셔널 서비스가 랜섬웨어 복구 보증 서비스를 구매할 때 이를 구성하거나 검증하는 경우, SnapLock로 보호되는 데이터를 복구할 수 없는 경우 NetApp는 서비스 크레딧을 발급합니다. 이 크레딧의 기준은 다음과 같습니다.

* 향후 송장에 서비스 크레딧을 적용할 수 있습니다. 크레딧의 한도는 약정 계약 금액(CCV)의 10%이며 구독 기준으로 지급됩니다.
* 크레딧은 관련 Keystone 주문의 활성 구독 기간 동안 제공됩니다.
* 월별 청구가 있는 구독의 경우 크레딧은 향후 12개월 동안 분할되며 구독 기간이 끝날 때까지 향후 Keystone 송장에 사용할 수 있습니다. 구독이 12개월 이내에 종료되는 경우 크레딧을 계속 사용하도록 갱신하거나 다른 NetApp 송장에 크레딧을 적용할 수 있습니다.
* 연간 구독의 경우 크레딧이 가능한 경우 다음 Keystone 송장에 적용됩니다. 향후 Keystone 송장이 없는 경우 크레딧을 다른 NetApp 송장에 적용할 수 있습니다.

