---
sidebar: sidebar 
permalink: concepts/supported-storage-capacity.html 
keywords: storage capacity, capacity definition, keystone STaaS storage capacity, 
summary: 지원되는 스토리지 용량입니다 
---
= Keystone에서 지원되는 스토리지 용량
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone 서비스 용량은 다음과 같습니다.



== 논리적 용량

고객이 Keystone 인프라에 배치한 데이터입니다. 모든 Keystone 용량은 논리적 용량을 기준으로 합니다. 예를 들어, 1TiB 파일이 Keystone 인프라에 저장된 경우 최소 1TiB 용량을 구매해야 합니다.



== 약속된 용량

서브스크립션 기간 동안 매월 청구되는 최소 논리적 용량:

* 용량은 각 서비스 레벨에 따라 커밋됩니다.
* 약정 용량 및 추가 서비스 레벨을 기간 동안 추가할 수 있습니다.




=== 약속된 용량의 변경

서브스크립션 기간 동안 약정 용량을 변경할 수 있습니다. 그러나 다음과 같은 몇 가지 전제 조건이 있습니다.

* 커밋된 용량은 특정 조건에 따라 감소될 수 있습니다. 자세한 내용은 을 참조하십시오 link:../concepts/capacity-requirements.html["용량 절감"].
* 가입 만료 90일 전에는 약정 용량을 늘릴 수 없습니다. 단, 12개월 추가 기간 동안 가입을 갱신해야 합니다.
* Cloud Manager 인터페이스 또는 Keystone Success Manager를 통해 커밋된 용량 변경을 요청할 수 있습니다. 변경 요청에 대한 자세한 내용은 을 참조하십시오 link:../concepts/gssc.html["NetApp 글로벌 서비스 지원 센터"].




== 사용된 용량

사용된 용량은 서비스에서 현재 사용되고 있는 용량(TiB 스토리지)을 나타냅니다. Keystone 서비스는 특정 서비스 수준에서 모든 볼륨의 논리적 사용된 크기(사용된 물리적 용량이 아님)의 합계를 계산하여 해당 서비스 수준에 대한 사용된 용량을 계산합니다.



== 버스트 용량

이 용량은 커밋된 용량을 초과한 사용된 용량입니다.


NOTE: 참고:

* Keystone 서비스는 커밋된 용량을 20% 넘게 제공합니다.
* 버스트 용량은 탄력적인 기준으로 사용할 수 있으며 평균 소비량에 대해 매일 청구됩니다.
* 최대 20%의 버스트 용량은 커밋된 용량과 동일한 속도로 충전됩니다.




== 비용 청구 용량

월별 청구서 = (약정 용량 [TiB] * 확정된 속도[$/TiB]) + (일별 평균 프로비저닝된 버스트 용량 [TiB] * 버스트 비율[$/TiB]) 월별 계산서에는 약정 용량에 따른 최소 요금이 포함됩니다.

월별 청구 요금은 일일 평균 사용 용량에 따라 최소 청구비 이상으로 다릅니다.
