---
sidebar: sidebar 
permalink: concepts/supported-storage-services.html 
keywords: storage, service, service definition, keystone STaaS services, 
summary: Keystone STaaS 서비스는 ONTAP 및 StorageGRID를 지원합니다. 
---
= Keystone에서 지원되는 스토리지
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaS 서비스는 ONTAP의 파일 및 블록 스토리지, StorageGRID 플랫폼의 오브젝트 스토리지, Cloud Volumes ONTAP의 데이터 관리 기능을 지원합니다.

Keystone STaaS는 스토리지에 대한 표준 및 옵션 서비스를 제공합니다.

* Keystone STaaS 표준 서비스 *: 표준 서비스는 기본 서비스 내에 포함되며 별도 비용이 청구되지 않습니다.

* Keystone STaaS 추가 서비스 *: 표준 Keystone STaaS 가입형 서비스 외에 추가 유틸리티 및 이점을 제공하는 유료 서비스입니다.

Keystone STaaS 서비스는 서로 공존할 수 있습니다. 예를 들어, 클라우드 스토리지 구독에서 파일, 블록 및 오브젝트 스토리지 구독을 상호 연결할 수 있습니다. 클라우드 서비스는 기존 스토리지 구독의 서비스 기간 중 언제든지 포함될 수 있습니다. 그러나 기존 파일, 블록 및 오브젝트 서브스크립션을 갱신하지 않을 계획이라면, 지난 90일 동안 클라우드 스토리지 구독을 추가할 수 없습니다.



== 파일, 블록 및 오브젝트 스토리지용 서비스

ONTAP 파일 및 블록 스토리지, StorageGRID 오브젝트 스토리지를 위한 Keystone STaaS 서비스는 다음 표에 설명된 다양한 기능 및 프로토콜을 지원합니다.

|===
| 스토리지 | 플랫폼 | 프로토콜 | 지원되는 기능 


 a| 
파일 스토리지
 a| 
ONTAP
 a| 
NFS 및 CIFS에 대해 설명합니다
 a| 
지원되는 ONTAP 기능:

* FlexVol
* FlexGroup
* Snapshot 복사본
* SnapMirror(비동기식)
* SnapVault
* SnapLock 엔터프라이즈
* FabricPool/클라우드 계층화
* SnapRestore
* 플랙스클론
* SnapCenter(라이센스는 포함되어 있지만 Keystone 서비스의 일부가 아니며 관리가 보장되지 않음)
* 자율적 랜섬웨어 방어 1




 a| 
블록 스토리지
 a| 
ONTAP
 a| 
FC 및 iSCSI
 a| 
지원되는 ONTAP 기능:

* FlexVol
* FlexGroup
* Snapshot 복사본
* SnapMirror(비동기식)
* SnapVault
* SnapLock 엔터프라이즈
* FabricPool/클라우드 계층화
* SnapRestore
* 플랙스클론
* SnapCenter(라이센스는 포함되어 있지만 Keystone 서비스의 일부가 아니며 관리가 보장되지 않음)




 a| 
오브젝트 스토리지
 a| 
StorageGRID
 a| 
S3
 a| 
여러 사이트에 걸쳐 여러 ILM(정보 수명 주기 관리) 정책을 지원합니다

|===

NOTE: ONTAP의 랜섬웨어 방어에 대한 자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["자율 랜섬웨어 보호"^].
각 사이트에는 별도의 가입이 필요합니다.



== 클라우드 스토리지용 서비스

Keystone STaaS는 클라우드 스토리지 서비스를 제공합니다. Keystone STaaS는 AWS(Amazon Web Services), Microsoft Azure 및 Google 클라우드 플랫폼에서 Cloud Volumes ONTAP 데이터 관리 기능을 지원합니다.


NOTE: NetApp은 Cloud Volumes ONTAP에 필요한 하이퍼스케일 기반 컴퓨팅, 스토리지 및 네트워크 서비스를 Keystone STaaS 가입의 일부로 제공하지 않습니다. 이러한 가입은 하이퍼스케일 클라우드 서비스 공급자로부터 직접 조달해야 합니다.
