---
sidebar: sidebar 
permalink: concepts/supported-storage-services.html 
keywords: storage, service, service definition, keystone STaaS services, 
summary: Keystone STaaS 서비스는 ONTAP 및 StorageGRID를 지원합니다. 
---
= Keystone에서 지원되는 스토리지
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaS는 NetApp 플랫폼과 Cloud Volumes ONTAP에서 통합, 블록 최적화, AFX 및 오브젝트 스토리지를 지원합니다. 각 스토리지 유형은 데이터 스토리지 유형(DST)으로 정의되며, 기본 구독에 포함된 표준 서비스와 선택적 추가 서비스를 통해 이용할 수 있습니다.



== Keystone STaaS 표준 및 추가 서비스

Keystone STaaS는 스토리지에 대한 표준 및 옵션 서비스를 제공합니다.

* Keystone STaaS 표준 서비스 *: 표준 서비스는 기본 서비스 내에 포함되며 별도 비용이 청구되지 않습니다.

* Keystone STaaS 추가 서비스 *: 표준 Keystone STaaS 가입형 서비스 외에 추가 유틸리티 및 이점을 제공하는 유료 서비스입니다.

여러 Keystone STaaS 서비스를 동시에 구독할 수 있습니다. 클라우드 서비스를 구독에 추가하면 통합 스토리지, 블록 최적화 스토리지 및/또는 오브젝트 스토리지와 동일한 기간을 공유합니다. 활성 스토리지 구독 중 언제든지 클라우드 서비스를 추가할 수 있습니다. 그러나 기존 통합 스토리지, 블록 최적화 스토리지 또는 오브젝트 스토리지 구독을 갱신하지 않을 경우 해당 구독의 마지막 90일 동안에는 클라우드 서비스를 추가할 수 없습니다.


NOTE: AFX 구독은 독립형이며, 동일한 구독 내에서 통합 스토리지, 블록 최적화 스토리지 또는 객체 스토리지와 결합할 수 없습니다. AFX를 다른 스토리지 유형과 함께 사용해야 하는 경우, 각각 별도의 구독으로 주문해야 합니다.



== 지원되는 데이터 스토리지 유형

Keystone STaaS 서비스는 통합, 블록 최적화, 오브젝트 및 AFX 스토리지를 제공하며 다양한 기능과 프로토콜을 지원합니다. 자세한 내용은 다음 표를 참조하십시오.

|===
| 데이터 스토리지 유형 | 설명 | 플랫폼 | 프로토콜 | 지원되는 기능 


 a| 
통합
 a| 
파일, 블록 및 S3 오브젝트 스토리지 포함
 a| 
AFF 및 FAS 시스템의 ONTAP
 a| 
FC, iSCSI, NFS, NFSv4/RDMA, NVMe/FC, NVMe/TCP, SMB, S3
 a| 
모든 ONTAP One 기능 지원



 a| 
블록 최적화
 a| 
블록 스토리지 포함
 a| 
NVMe/TCP, NVMe/FC, FC, iSCSI
 a| 
FC 및 iSCSI
 a| 
ONTAP One for SAN의 모든 기능을 지원합니다.



 a| 
AFX
 a| 
분산형 스토리지 플랫폼에 파일 및 오브젝트 스토리지 포함
 a| 
AFX 시스템의 ONTAP
 a| 
NFSv3, NFSv4/RDMA, pNFS, SMB, S3
 a| 
모든 ONTAP One 기능 지원



 a| 
객체
 a| 
오브젝트 스토리지 포함
 a| 
StorageGRID
 a| 
S3
 a| 
모든 StorageGRID 기능을 지원합니다

|===
ONTAP One에 대해 자세히 알아보려면 다음을 참조하세요. link:https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP 라이센스 개요"^] 그리고 link:https://www.netapp.com/blog/ontap-one/["ONTAP One: ONTAP의 모든 기능을 이제 하나로"^] .



== 클라우드 스토리지용 서비스

Keystone STaaS는 클라우드 스토리지 서비스를 제공합니다. Keystone STaaS는 AWS(Amazon Web Services), Microsoft Azure 및 Google 클라우드 플랫폼에서 Cloud Volumes ONTAP 데이터 관리 기능을 지원합니다.


NOTE: Cloud Volumes ONTAP에 필요한 하이퍼스케일러 기반 컴퓨팅, 스토리지 및 네트워크 서비스는 Keystone STaaS 구독의 일부로 NetApp에서 제공하지 않습니다. 이러한 구독은 하이퍼스케일러 클라우드 서비스 공급자로부터 직접 구매해야 합니다.
