---
sidebar: sidebar 
permalink: concepts/supported-storage-services.html 
keywords: storage service, service definition, keystone STaaS storage service, 
summary: 지원되는 스토리지 서비스 
---
= 지원되는 스토리지 서비스
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone 서비스는 ONTAP, 파일 및 블록의 기본 스토리지 유형을 지원합니다. 또한 StorageGRID 플랫폼용 오브젝트 스토리지와 Cloud Volumes ONTAP의 데이터 관리 기능도 지원합니다.

서비스 수준에 대한 자세한 내용은 을 참조하십시오 link:../concepts/service-levels.html["Keystone의 서비스 수준"].



== 기본 스토리지 서비스

파일 및 블록을 위한 기본 스토리지 서비스는 SnapMirror, SnapVault 및 Snapshot과 같은 NetApp 기술을 활용하여 기본 데이터 보호 서비스를 제공합니다. NetApp 스토리지 대상에 대한 데이터 계층화도 파일 및 블록 스토리지 서비스 계층에 기본적으로 포함됩니다. 또한 데이터 보호 및 계층화를 위한 애드온 서비스를 선택할 수 있습니다. 추가 서비스에 대한 자세한 내용은 을 참조하십시오 link:../concepts/adp.html["고급 데이터 보호"] 및 link:../concepts/data-tiering.html["데이터 계층화"].

|===
| 스토리지 서비스 | 기초 | 지원되는 기능 | 프로토콜 


 a| 
파일 스토리지
| ONTAP 기술 기반 | 지원되는 ONTAP 기능: FlexVol FlexGroup 스냅샷 복사본 SnapMirror(비동기식) SnapVault SnapLock 엔터프라이즈 FabricPool/클라우드 계층화 복원 클론 SnapCenter(라이센스가 포함되어 있지만 Keystone 서비스의 일부가 아니며 보장된 관리가 제공되지 않음) | NFS 및 CIFS에 대해 설명합니다. 


 a| 
블록 스토리지
| ONTAP 기술 기반 | 지원되는 ONTAP 기능: FlexVol FlexGroup 스냅샷 복사본 SnapMirror(비동기식) SnapVault SnapLock 엔터프라이즈 FabricPool/클라우드 계층화 복원 클론 SnapCenter(라이센스가 포함되어 있지만 Keystone 서비스의 일부가 아니며 보장된 관리가 제공되지 않음) | FC 및 iSCSI 


 a| 
오브젝트 스토리지
| StorageGRID 플랫폼 기반 | 여러 사이트에서 여러 ILM(정보 수명 주기 관리) 정책을 지원합니다. 참고: 각 사이트에는 별도의 구독이 있어야 합니다. | S3 
|===


== 클라우드 스토리지 서비스

Keystone은 AWS(Amazon Web Services), Microsoft Azure, Google 클라우드 플랫폼에서 Cloud Volumes ONTAP를 위한 데이터 관리 기능을 지원합니다. 이 서비스는 기존 구독과 상호 연계할 수 있습니다. 클라우드 서비스는 서비스 기간 중 언제든지 포함될 수 있습니다. 그러나 가입을 갱신하지 않을 계획이라면 가입 후 90일 이내에 클라우드 서비스를 포함시킬 수 없습니다.


NOTE: NetApp은 하이퍼스케일 기반 컴퓨팅 및 스토리지 인프라를 Keystone 서브스크립션의 일부로 제공하지 않으며 하이퍼스케일 클라우드 서비스 공급자로부터 조달해야 합니다.
