---
sidebar: sidebar 
permalink: concepts/support-services.html 
keywords: Keystone support, service request, support ticket 
summary: NetApp 지원 사이트를 이용하여 지원 사례를 생성하거나 Keystone 구독 관련 연락처 정보를 찾아보세요. 
---
= Keystone에 대한 도움을 받으십시오
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp은 Keystone 고객에게 운영 서비스를 제공합니다. 고객은 전담 Keystone 성공 관리자(KSM), 직접 지원 연락 옵션, ITOM 솔루션을 통한 사전 예방적 모니터링 서비스를 이용할 수 있습니다.



== NetApp 지원 서비스

NetApp은 Keystone 고객에게 원격으로 운영 서비스를 제공합니다. 이러한 서비스는 자산 및 구성 관리, 용량 및 성능 관리, 변경 관리, 이벤트 및 사고 관리, 서비스 요청 처리, 보고 등 다양한 스토리지 관리 활동을 포괄합니다.

.Keystone 성공 관리자
담당 KSM(Keystone Service Manager)은 고객과 긴밀히 협력하여 Keystone 서비스를 관리하고 주간 또는 월간 청구 및 운영 보고서를 제공합니다. 구체적인 책임 사항은 NetApp Keystone 계약서에 명시되어 있습니다.



== 지원 팀에 문의하십시오

Keystone 구독에 문제가 발생하면 NSS 자격 증명을 사용하여 link:https://support.netapp.com["NetApp 지원 사이트"^]에 로그인하고 지원 사례를 생성하세요.

NSS 로그인 정보가 없는 경우 link:https://mysupport.netapp.com/site/user/registration["계정 등록"^] 구독에 포함된 노드 중 하나의 일련 번호(SN)를 사용하십시오.

스크린샷이 포함된 단계별 지침은 link:https://kb.netapp.com/nss/Support_Site/How_to_open_a_technical_support_case["기술 지원 사례를 여는 방법"^]을 참조하십시오.

지원 담당자와 직접 통화하려면 다음 번호 중 하나로 전화하십시오.

* 미국/캐나다: 888 463 8277
* 유럽: 00 800 44 638277
* 인도: 000 800 100 8948
* 더 많은 글로벌 수치: link:https://www.netapp.com/company/contact-us/support/["https://www.netapp.com/company/contact-us/support/"^]




== 지원 모니터링

NetApp은 ITOM 모니터링 솔루션을 사용하여 제품 및 구독 서비스의 상태를 사전에 모니터링하고 문제 해결을 위해 NetApp Keystone 환경에 연결합니다.



== 추가 리소스

Keystone 서비스에 대한 자세한 내용은 다음을 참조하십시오.

* link:https://www.netapp.com/us/solutions/keystone/index.aspx["NetApp Keystone"^]
* link:https://docs.netapp.com["NetApp 제품 설명서"^]


* 관련 정보 *

* link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_Identify_Serial_Number_of_ONTAP_Platform["ONTAP 플랫폼의 일련 번호를 확인하는 방법"^]
* link:https://kb.netapp.com/hybrid/StorageGRID/Maintenance/Which_serial_number_to_use_when_creating_StorageGRID_technical_support_case["StorageGRID 기술 지원 케이스를 생성할 때 사용할 일련 번호"^]

