---
sidebar: sidebar 
permalink: concepts/supported-storage-services.html 
keywords: storage service, service definition, keystone STaaS storage service, 
summary: 지원되는 스토리지 서비스 
---
= 지원되는 스토리지 서비스
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone 서비스는 파일 및 블록 스토리지와 같은 기본 스토리지 유형의 ONTAP를 지원합니다. StorageGRID 플랫폼용 오브젝트 스토리지도 지원합니다. Cloud Volumes ONTAP의 데이터 관리 기능도 지원됩니다.

서비스 수준에 대한 자세한 내용은 을 참조하십시오 link:../concepts/service-levels.html["Keystone의 서비스 수준"]



== 기본 스토리지 서비스

|===
| 스토리지 서비스 | 기초 | 지원되는 기능 | 프로토콜 


 a| 
파일 스토리지
| ONTAP 기술 기반 | 지원되는 ONTAP 기능: FlexVol FlexGroup 스냅샷 복사본 SnapMirror(비동기식) SnapVault SnapLock 엔터프라이즈 FabricPool/클라우드 계층화 복원 클론 SnapCenter(라이센스가 포함되어 있지만 Keystone 서비스의 일부가 아니며 보장된 관리가 제공되지 않음) | NFS, CIFS 및 S3(FabricPool 타겟에 사용) 


 a| 
블록 스토리지
| ONTAP 기술 기반 | 지원되는 ONTAP 기능: FlexVol FlexGroup 스냅샷 복사본 SnapMirror(비동기식) SnapVault SnapLock 엔터프라이즈 FabricPool/클라우드 계층화 복원 클론 SnapCenter(라이센스가 포함되어 있지만 Keystone 서비스의 일부가 아니며 보장된 관리가 제공되지 않음) | FC, iSCSI 및 S3(FabricPool 타겟에 사용) 


 a| 
오브젝트 스토리지
| StorageGRID 플랫폼 기반 | 여러 사이트에서 여러 ILM(정보 수명 주기 관리) 정책을 지원합니다. 참고: 각 사이트에는 별도의 구독이 있어야 합니다. | S3 
|===

NOTE: NetApp 스토리지 타겟에 대한 데이터 계층화는 기본적으로 파일 및 블록 스토리지 서비스 계층에 포함됩니다.

데이터 계층화에 대한 자세한 내용은 를 참조하십시오 link:../concepts/data-tiering.html["데이터 계층화"]데이터 보호 서비스에 대한 자세한 내용은 을 참조하십시오 link:../concepts/adp.html["고급 데이터 보호"]



== 클라우드 스토리지 서비스

Keystone은 AWS, Azure 및 Google_에서 지원되는 Cloud Volumes ONTAP의 _ 데이터 관리 기능을 지원합니다. 이 서비스는 기존 구독과 상호 연계할 수 있습니다. 클라우드 서비스는 서비스 기간 중 언제든지 포함될 수 있습니다. 그러나 가입을 갱신하지 않을 계획이라면 가입 후 90일 이내에 클라우드 서비스를 포함시킬 수 없습니다.


NOTE: NetApp은 하이퍼스케일 기반 컴퓨팅 및 스토리지 인프라를 Keystone 서브스크립션의 일부로 제공하지 않으며 하이퍼스케일 클라우드 서비스 공급자로부터 이를 조달해야 합니다.
