---
sidebar: sidebar 
permalink: concepts/supported-storage-capacity.html 
keywords: storage capacity, capacity definition, keystone STaaS storage capacity, 
summary: NetApp Keystone STaaS 서비스가 지원하는 스토리지 용량의 유형에 대해 알아보십시오. 
---
= Keystone에서 지원되는 스토리지 용량
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone STaaS 서비스는 다양한 유형의 스토리지 용량을 지원합니다. 서로 다른 용량 용어를 이해하면 Keystone을 사용하는 데 도움이 될 수 있습니다.



== 논리적 용량

고객이 Keystone 인프라에 배치한 데이터입니다. 모든 Keystone 용량은 논리적 용량을 기준으로 합니다. 예를 들어, 1TiB 파일이 Keystone 인프라에 저장된 경우 최소 1TiB 용량을 구매해야 합니다.



== 약속된 용량

서브스크립션 기간 동안 매월 청구되는 최소 논리적 용량:

* 용량은 각 서비스 레벨에 따라 커밋됩니다.
* 약정 용량 및 추가 서비스 레벨을 기간 동안 추가할 수 있습니다.




=== 약속된 용량의 변경

서브스크립션 기간 동안 약정 용량을 변경할 수 있습니다. 그러나 다음과 같은 몇 가지 전제 조건이 있습니다.

* 커밋된 용량은 특정 조건에 따라 감소될 수 있습니다. 자세한 내용은 을 참조하십시오 link:../concepts/capacity-requirements.html["용량 절감"].
* 구독이 12개월 추가 기간 동안 갱신되지 않는 한, 약정 용량은 구독이 만료되기 90일 전에 늘릴 수 없습니다.
* BlueXP 인터페이스 또는 Keystone 성공 관리자(KSM)를 통해 약정 용량에 대한 변경을 요청할 수 있습니다. 변경 요청에 대한 자세한 내용은 을 link:../concepts/gssc.html["NetApp Keystone 지원"]참조하십시오.




== 사용된 용량

사용된 용량은 서비스에서 현재 사용되고 있는 용량(TiB 스토리지)을 나타냅니다. 다음 값의 합계입니다.

* 모든 인스턴스와 사용자 데이터 유형(복사본, 미러링된 복사본, 버전 등)을 저장하는 데 사용되는 논리적 용량입니다.
* 원본 볼륨 크기의 10%를 초과하는 클론 볼륨을 저장하는 데 사용되는 논리적 용량입니다.
* 스냅샷 복사본의 차등 데이터를 저장하는 데 사용되는 물리적 용량
* 할당된 물리적 용량입니다.




== 버스트 용량

Keystone 서비스를 사용하면 서비스 수준에 대해 커밋된 용량 외에 추가 용량을 사용할 수 있습니다. 버스트 용량 사용량입니다. 다음 사항에 유의하십시오.

* 최대 용량은 Keystone 계약에 합의됩니다. 일반적으로 커밋된 용량보다 20% 높게 설정되며 커밋된 용량과 동일한 속도로 충전됩니다.
* 버스트 용량은 탄력적인 기준으로 사용할 수 있으며 평균 소비량에 대해 매일 청구됩니다.




== 비용 청구 용량

월별 청구서 = (약정 용량 [TiB] * 확정된 속도[$/TiB]) + (일별 평균 프로비저닝된 버스트 용량 [TiB] * 버스트 비율[$/TiB]) 월별 계산서에는 약정 용량에 따른 최소 요금이 포함됩니다.

월별 청구 요금은 일일 평균 사용 용량에 따라 최소 청구비 이상으로 다릅니다.
