---
sidebar: sidebar 
permalink: concepts/supported-storage-services.html 
keywords: storage, service, service definition, keystone STaaS services, 
summary: Keystone STaaS 서비스는 ONTAP 및 StorageGRID를 지원합니다. 
---
= Keystone에서 지원되는 스토리지
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
버전 3(v3)용 Keystone STaaS 서비스는 NetApp 및 Cloud Volumes ONTAP의 통합, 블록 최적화 및 개체 스토리지를 지원합니다.

각 저장 유형에는 다음이 포함됩니다.

* *통합 스토리지*: NetApp ONTAP AFF와 FAS 시스템에서 사용할 수 있는 파일, 블록 및 S3 개체 스토리지를 모두 포함합니다.
* *블록 최적화 스토리지*: NetApp ONTAP ASA 시스템에서 사용 가능한 블록 스토리지가 포함됩니다.
* *객체 스토리지*: NetApp StorageGRID 시스템에서 사용할 수 있는 객체 스토리지를 포함합니다.


Keystone STaaS는 스토리지에 대한 표준 및 옵션 서비스를 제공합니다.

* Keystone STaaS 표준 서비스 *: 표준 서비스는 기본 서비스 내에 포함되며 별도 비용이 청구되지 않습니다.

* Keystone STaaS 추가 서비스 *: 표준 Keystone STaaS 가입형 서비스 외에 추가 유틸리티 및 이점을 제공하는 유료 서비스입니다.

Keystone STaaS 서비스는 동시에 사용할 수 있습니다. 예를 들어, 클라우드 스토리지 구독은 통합, 블록 최적화, 객체 스토리지 구독과 동일한 기간을 가질 수 있습니다. 클라우드 서비스는 기존 스토리지 구독의 서비스 기간 중 언제든지 포함될 수 있습니다. 단, 기존 통합, 블록 최적화 또는 객체 스토리지 구독을 갱신할 계획이 없는 경우, 구독 기간의 마지막 90일 동안은 클라우드 스토리지 구독을 추가할 수 없습니다.



== 통합, 블록 최적화 및 객체 스토리지를 위한 서비스

통합, 블록 최적화 및 객체 스토리지를 위한 Keystone STaaS 서비스는 여러 기능과 프로토콜을 지원하며, 다음 표에 설명되어 있습니다.

|===
| 스토리지 | 플랫폼 | 프로토콜 | 지원되는 기능 


 a| 
유니파이드 스토리지
 a| 
ONTAP
 a| 
NFS 및 CIFS에 대해 설명합니다
 a| 
모든 ONTAP One 기능 지원



 a| 
블록 최적화된 스토리지
 a| 
ONTAP
 a| 
FC 및 iSCSI
 a| 
모든 ONTAP One 기능 지원



 a| 
오브젝트 스토리지
 a| 
StorageGRID
 a| 
S3
 a| 
모든 ONTAP One 기능 지원

|===
ONTAP One에 대해 자세히 알아보려면 다음을 참조하세요. link:https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP 라이센스 개요"^] 그리고 link:https://www.netapp.com/blog/ontap-one/["ONTAP One: ONTAP의 모든 기능을 이제 하나로"^] .



== 클라우드 스토리지용 서비스

Keystone STaaS는 클라우드 스토리지 서비스를 제공합니다. Keystone STaaS는 AWS(Amazon Web Services), Microsoft Azure 및 Google 클라우드 플랫폼에서 Cloud Volumes ONTAP 데이터 관리 기능을 지원합니다.


NOTE: NetApp은 Cloud Volumes ONTAP에 필요한 하이퍼스케일 기반 컴퓨팅, 스토리지 및 네트워크 서비스를 Keystone STaaS 가입의 일부로 제공하지 않습니다. 이러한 가입은 하이퍼스케일 클라우드 서비스 공급자로부터 직접 조달해야 합니다.
