---
sidebar: sidebar 
permalink: concepts/supported-storage-capacity.html 
keywords: storage capacity, capacity definition, keystone STaaS storage capacity, 
summary: NetApp Keystone STaaS 서비스 버전 3에서 지원하는 스토리지 용량 유형에 대해 알아보세요. 
---
= Keystone의 스토리지 용량 유형
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaS는 스토리지 용량을 측정, 확정 및 청구하는 데 여러 용어를 사용합니다. 이러한 용어를 이해하면 구독 계획을 세우고 사용량 보고서와 청구서를 해석하는 데 도움이 됩니다.



== 논리적 용량

이는 스토리지 어레이가 제공하는 데이터 효율성이 적용되기 전에 사용자 데이터를 저장하는 데 필요한 저장 용량입니다.



== 약속된 용량

서브스크립션 기간 동안 매월 청구되는 최소 논리적 용량:

* 용량은 통합 스토리지 또는 블록 최적화 스토리지의 경우 각 성능 서비스 수준 인스턴스에, 또는 AFF 클러스터별로 할당됩니다.
* 약정 용량과 추가 성능 서비스 수준은 계약 기간 중에 추가할 수 있습니다.




=== 약속된 용량의 변경

구독 기간 동안 특정 조건에 따라 약정된 용량을 변경할 수 있습니다. 용량 증감 규칙에 대한 자세한 내용은 link:../concepts/capacity-requirements.html["Keystone 성능 서비스 수준에 필요한 용량"]를 참조하십시오. 변경을 요청하려면 Keystone Success Manager(KSM)에게 문의하거나 link:../concepts/support-services.html["NetApp 지원"]를 클릭하십시오.



== 사용된 용량

사용 용량은 서비스에서 현재 사용 중인 용량(스토리지 TiB)을 나타냅니다. 데이터 스토리지 유형에 따라 계산 방식이 다릅니다.

* *통합 또는 블록 최적화 스토리지*: 소비 용량은 주문 과정에서 선택한 용량 유형(논리적 또는 물리적)에 따라 계산됩니다.  계산은 성능 서비스 수준 인스턴스별로 수행됩니다.
+
.. *논리적 용량*: 다음의 합계입니다.
+
*** 복사본, 미러링된 복사본, 버전 및 복제본과 같은 모든 인스턴스와 고객 데이터 유형을 저장하기 위한 스토리지 어레이 데이터 효율성 이전의 측정된 논리적 용량입니다.
*** 스냅샷과 특정 클론의 메타데이터와 차등 데이터를 저장하는 데 사용되는 물리적 용량입니다.
*** 두껍게 프로비저닝된 물리적 용량.


.. *신체적 능력*: 다음의 합계입니다.
+
*** 복사본, 미러링된 복사본, 버전 및 클론과 같은 모든 인스턴스 및 유형의 고객 데이터를 저장하기 위한 스토리지 어레이 데이터 효율성 이후의 측정된 물리적 용량입니다.
*** 스냅샷의 메타데이터와 차등 데이터를 저장하는 데 사용되는 물리적 용량입니다.
*** 두껍게 프로비저닝된 물리적 용량.




* *AFX 스토리지*: AFX 클러스터별로 다음과 같이 합산하여 계산됩니다.
+
** 복사본, 미러링된 복사본, 버전 및 클론과 같은 모든 인스턴스 및 유형의 고객 데이터를 저장하기 위한 스토리지 어레이 데이터 효율성 이후의 측정된 물리적 용량입니다.
** 스냅샷의 메타데이터와 차등 데이터를 저장하는 데 사용되는 물리적 용량입니다.
** 두껍게 프로비저닝된 물리적 용량.


* *오브젝트 스토리지*: 소비 용량은 모든 노드에서 모든 인스턴스와 고객 데이터 유형을 저장하는 데 사용된 측정된 물리적 용량으로 계산됩니다. 이 계산은 구성된 정보 수명 주기 관리(ILM) 정책을 기반으로 합니다.
* *Cloud Volumes ONTAP*: 소비된 용량은 모든 Cloud Volumes ONTAP 볼륨의 측정된 프로비저닝된 논리적 용량으로 계산됩니다.




== 버스트 용량

NetApp Keystone STaaS 서비스를 사용하면 성능 서비스 수준에 맞춰 약정된 용량 외에 추가 용량을 사용할 수 있습니다. 이를 버스트 용량 사용량이라고 합니다.

다음 사항에 유의하십시오.

* 버스트 용량 제한은 Keystone 주문 시 합의됩니다. 일반적으로 성능 서비스 레벨 인스턴스 또는 AFF 클러스터별로 약정된 용량의 20%로 기본 설정되며, 통합 스토리지 및 블록 최적화 스토리지의 경우 약정된 용량의 40% 또는 60%로 버스트 용량 제한을 선택할 수 있는 추가 옵션이 제공됩니다.
* 버스트 용량 사용량은 선택한 데이터 스토리지 유형(DST) 및 성능 서비스 수준에 해당하는 커밋된 용량과 동일한 요율로 청구됩니다.
* Keystone STaaS 서비스는 시작일로부터 60일 동안 일괄 면제 기간을 제공합니다.




== 비용 청구 용량

월별 청구서 = (약정 용량 [TiB] * 확정된 속도[$/TiB]) + (일별 평균 프로비저닝된 버스트 용량 [TiB] * 버스트 비율[$/TiB]) 월별 계산서에는 약정 용량에 따른 최소 요금이 포함됩니다.

월별 청구 요금은 일일 평균 사용 용량에 따라 최소 청구비 이상으로 다릅니다.
