---
sidebar: sidebar 
permalink: concepts/data-tiering.html 
keywords: add-on services, add-on, data tiering 
summary: 애드온, 추가 서비스 세부 정보, 데이터 계층화 
---
= 데이터 계층화
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
기본적으로 Keystone 기본 서비스에는 덜 자주 사용되는 데이터를 식별하는 구독 파일 및 블록 서비스를 통한 계층화 기능이 포함되며 NetApp이 소유, 구축 및 관리하는 콜드 스토리지에 계층화합니다. 콜드 데이터를 엔터프라이즈 클라우드 스토리지와 같은 타사 스토리지에 계층화하려는 경우 추가 서비스로 계층화를 사용할 수 있습니다.

계층화 애드온 서비스는 데이터가 AWS S3, Azure Blob 및 EMC ECS와 같은 타사 스토리지로 계층화할 경우에만 필요합니다.

기본 스토리지 및 클라우드 스토리지 서비스에 대한 자세한 내용은 를 참조하십시오 link:../concepts/supported-storage-services.html["지원되는 스토리지 서비스"].

서비스 수준에 대한 자세한 내용은 을 참조하십시오 link:../concepts/service-levels.html["Keystone의 서비스 수준"].

계층화 기능은 NetApp FabricPool 기술을 활용하여 사내 또는 사외에서 데이터를 저비용 오브젝트 스토리지 계층으로 자동 계층화할 수 있습니다. 이 기능을 사용하면 자주 액세스하지 않는 데이터는 합의된 서비스에 따라 사내 또는 클라우드의 저렴한 스토리지로 자동으로 계층됩니다.

애드온 계층화 서비스를 사용하면 Extreme, Premium, Performance, Standard 및 Value 계층에서 Object Target으로 계층화할 수 있습니다. 핫 계층과 콜드 계층은 별도로 측정 및 청구됩니다.

가격 변경 없이 데이터 계층화를 언제든지 추가할 수 있으며 핫:콜드 비율 측면에서는 유연성을 더욱 높여줍니다. 계층화할 Hot:Cold 데이터의 비율은 고정되어 있지 않으며 계층화된 물리적 블록 수는 별도로 측정됩니다.

자세한 내용은 다음 계산을 참조하십시오.

콜드 스토리지 계층의 타겟이 다음과 같은 경우:

* Value 계층(최대 500TiB), Object Tier(> 500TiB), 기존 SGWs 그리드(고객 소유) – 추가 비용이 없으며 기본 스토리지 서비스에 포함됩니다.
* 퍼블릭 클라우드(AWS, Azure, Google) 및 기타 타사 지원 오브젝트 스토리지 - 계층 아웃 비용으로 커밋된 데이터 용량에 대해 추가 비용이 부과됩니다.


애드온 계층화 구독에 따른 비용은 일회성 비용이 아닙니다. Keystone 온프레미스 파일 및 블록 서비스와 타사 지원 오브젝트 스토리지 대상 간의 계층화 관계를 유지하려면 전체 기간 동안 IT 비용을 지불해야 합니다.

이 오퍼링은 퍼블릭 클라우드/하이퍼스케일 인프라 비용이 아닌, 더 저렴한 타겟 스토리지에 콜드 데이터를 계층화할 수 있는 기능만 제공합니다.


NOTE: NetApp은 하이퍼스케일 기반 컴퓨팅 및 스토리지 인프라를 Keystone 서브스크립션의 일부로 제공하지 않으며 하이퍼스케일 클라우드 서비스 공급자로부터 조달해야 합니다.
