---
sidebar: sidebar 
permalink: installation/install-itom-linux.html 
keywords: Linux installation, ITOM Collector installation 
summary: Linux 기반 시스템에 ITOM Collector 소프트웨어를 설치합니다. 
---
= Linux 시스템에 Keystone ITOM Collector를 설치하세요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
스토리지 환경에서 메트릭 데이터를 수집하는 ITOM Collector를 설치하려면 몇 가지 단계를 완료하세요. 요구 사항에 따라 Windows 또는 Linux 시스템에 설치할 수 있습니다.


NOTE: Keystone 지원 팀은 ITOM Collector 설정 파일을 다운로드할 수 있는 동적 링크를 제공합니다. 이 파일은 2시간 후에 만료됩니다.

Windows 시스템에 ITOM Collector를 설치하려면 을 link:../installation/install-itom-windows.html["Windows 시스템에 ITOM Collector를 설치합니다"]참조하십시오.

Linux 서버에 소프트웨어를 설치하려면 다음 단계를 수행하십시오.

.시작하기 전에
* Linux 설치 스크립트에 Bourne 셸을 사용할 수 있는지 확인합니다.
*  `vim-common`패키지를 설치하여 ITOM Collector 설치 파일에 필요한 * xxd * 바이너리를 가져옵니다.
* ITOM Collector를 루트가 아닌 사용자로 실행하려면 가 `sudo package` 설치되어 있어야 합니다.


.단계
. Linux 서버에 ITOM Collector 설정 파일을 다운로드합니다.
. 서버에서 터미널을 열고 다음 명령을 실행하여 권한을 변경하고 바이너리를 실행 파일로 만듭니다.
`# chmod +x <installer_file_name>.bin`
. 다음 명령을 실행하여 ITOM Collector 설정 파일을 시작합니다.
`#./<installer_file_name>.bin`
. 설치 파일을 실행하면 다음 메시지가 표시됩니다.
+
.. 최종 사용자 사용권 계약(EULA)에 동의합니다.
.. 설치에 대한 사용자 세부 정보를 입력합니다.
.. 설치 상위 디렉토리를 지정합니다.
.. 수집기 크기를 선택합니다.
.. 해당하는 경우 프록시 세부 정보를 제공합니다.
+
각 프롬프트마다 기본 옵션이 표시됩니다. 특정 요구 사항이 없는 경우 기본 옵션을 선택하는 것이 좋습니다. Enter * 키를 눌러 기본 옵션을 선택합니다. 설치가 완료되면 ITOM Collector가 성공적으로 설치되었음을 확인하는 메시지가 표시됩니다.





[NOTE]
====
* ITOM Collector 설치 파일은 서비스 재시작 및 메모리 덤프를 처리하기 위해 에 `/etc/sudoers` 추가합니다.
* Linux 서버에 ITOM Collector를 설치하면 * ITOM * 이라는 기본 사용자가 만들어져 루트 Privileges 없이 ITOM Collector를 실행할 수 있습니다. 다른 사용자를 선택하거나 루트로 실행할 수 있지만 Linux 설치 스크립트로 만든 ITOM 사용자를 사용하는 것이 좋습니다.


====
.다음 단계
설치가 완료되면 Keystone 지원 팀에 문의하여 ITOM 지원 포털을 통해 ITOM Collector가 성공적으로 설치되었는지 확인합니다. 확인 후 Keystone 지원 팀은 추가 장치 검색 및 모니터링 설정을 포함하여 ITOM Collector를 원격으로 구성하고 구성이 완료되면 확인 메시지를 보냅니다. 문의 사항이나 추가 정보는 keystone.services@ NetApp.com에 문의하십시오.
