---
sidebar: sidebar 
permalink: installation/linux-installation.html 
keywords: Linux installation Keystone, Linux Collector installation 
summary: YUM 소프트웨어 저장소에서 Keystone Collector 소프트웨어를 설치합니다. 
---
= Linux 시스템에 Keystone Collector를 설치합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
RPM 또는 데비안 패키지를 사용하여 Linux 서버에 Keystone Collector 소프트웨어를 설치할 수 있습니다. Linux 배포에 따라 설치 단계를 따릅니다.

[role="tabbed-block"]
====
.RPM 사용
--
. Keystone Collector 서버로 SSH를 수행하고 로 승격합니다 `root` 권한.
. Keystone 공개 서명을 가져옵니다.
`# rpm --import https://keystone.netapp.com/repo1/RPM-GPG-NetApp-Keystone-20251020`
. RPM 데이터베이스에서 Keystone Billing Platform의 지문을 확인하여 올바른 공개 인증서가 가져왔는지 확인하세요.
`# rpm -qa gpg-pubkey --qf '%{Description}'|gpg --show-keys --fingerprint` 올바른 지문은 다음과 같습니다.
`9297 0DB6 0867 22E7 7646 E400 4493 5CBB C9E9 FEDC`
. 다운로드 `keystonerepo.rpm` 파일:
`curl -O https://keystone.netapp.com/repo1/keystonerepo.rpm`
. 파일의 진위 여부를 확인하세요.
`rpm --checksig -v keystonerepo.rpm` 진짜 파일의 서명은 다음과 같습니다.
`Header V4 RSA/SHA512 Signature, key ID c9e9fedc: OK`
. YUM 소프트웨어 저장소 파일을 설치합니다.
`# yum install keystonerepo.rpm`
. Keystone repo가 설치되면 YUM 패키지 관리자를 통해 Keystone-Collector 패키지를 설치합니다.
+
`# yum install keystone-collector`

+
Red Hat Enterprise Linux 9의 경우 다음 명령을 실행하여 keystone-collector 패키지를 설치합니다. 
`# yum install keystone-collector-rhel9`



--
.데비안 사용하기
--
. Keystone Collector 서버에 SSH로 연결하고 권한을
`sudo su` 상승합니다. `root`
.  `keystone-sw-repo.deb`다음 파일을 다운로드합니다.
`curl -O https://keystone.netapp.com/downloads/keystone-sw-repo.deb`
. Keystone 소프트웨어 저장소 파일을 설치합니다.
`# dpkg -i keystone-sw-repo.deb`
. 패키지 목록 업데이트:
`# apt-get update`
. Keystone 리포지토리가 설치되면 키스톤-수집기 패키지를 설치합니다.
`# apt-get install keystone-collector`


--
====

NOTE: 설치를 완료하면 Keystone Collector 관리 터미널 사용자 인터페이스(TUI) 유틸리티를 사용하여 구성 및 모니터링 작업을 수행할 수 있습니다. Enter 및 화살표 키와 같은 다양한 키보드 컨트롤을 사용하여 옵션을 선택하고 이 TUI를 탐색할 수 있습니다. 을 참조하십시오 link:../installation/configuration.html["Keystone Collector 구성"] 및 link:../installation/monitor-health.html["시스템 상태를 모니터링합니다"] 를 참조하십시오.
