---
sidebar: sidebar 
permalink: installation/linux-prereqs.html 
keywords: prerequisites, Linux 
summary: Linux 시스템에 Keystone Collector 설치를 위한 사전 요구사항 
---
= Linux 시스템 요구 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Linux 시스템에 Keystone Collector를 설치하는 데 필요한 몇 가지 구성이 있습니다.

.Linux 서버의 필수 구성 요소:
* 운영 체제: CentOS 7 또는 Red Hat Enterprise Linux 8.6 이상
* 약어 시간 동기화됨
* 표준 Linux 소프트웨어 저장소에 대한 액세스


동일한 서버에 다음과 같은 타사 패키지도 있어야 합니다.

* 포드만(POD 매니저)
* SOS(SOS
* 연대기
* Python 3 (3.6.8 ~ 3.3.13)


.Keystone Collector 서버 VM의 사전 요구 사항:
* 코어: CPU 2개
* RAM: 4GB RAM
* 디스크 공간: 50GB vDisk




== 기타 요구 사항

다음과 같은 일반 요구 사항이 충족되는지 확인합니다.



=== 네트워킹 요구 사항

Keystone 수집기의 네트워킹 요구사항은 다음 표에 나와 있습니다.


NOTE: Keystone 수집기는 인터넷 연결이 필요합니다. 기본 게이트웨이(NAT를 통해) 또는 HTTP 프록시를 통해 직접 라우팅하여 인터넷 연결을 제공할 수 있습니다. 두 가지 변형 모델이 모두 여기에 설명되어 있습니다.

|===


| 출처 | 목적지 | 서비스 | 프로토콜 및 포트 | 범주 | 목적 


 a| 
Keystone Collector(Keystone ONTAP용)
 a| 
Active IQ Unified Manager(유니파이드 매니저)
 a| 
HTTPS
 a| 
TCP 443
 a| 
필수(Keystone ONTAP를 사용하는 경우)
 a| 
ONTAP에 대한 Keystone Collector 사용 메트릭 수집



 a| 
Keystone Collector(Keystone StorageGRID용)
 a| 
StorageGRID 관리 노드
 a| 
HTTPS
 a| 
TCP 443
 a| 
필수(Keystone StorageGRID를 사용하는 경우)
 a| 
StorageGRID에 대한 Keystone Collector 사용 메트릭 수집



 a| 
Keystone Collector(일반)
 a| 
인터넷(나중에 제공된 URL 요구 사항에 따라)
 a| 
HTTP, HTTPS
 a| 
TCP 80, TCP 443
 a| 
필수(인터넷 연결)
 a| 
Keystone Collector 소프트웨어, OS 업데이트 및 메트릭 업로드



 a| 
Keystone Collector(일반)
 a| 
고객 HTTP 프록시
 a| 
HTTP 프록시
 a| 
고객 프록시 포트
 a| 
필수(인터넷 연결)
 a| 
Keystone Collector 소프트웨어, OS 업데이트 및 메트릭 업로드



 a| 
Keystone Collector(일반)
 a| 
고객 DNS 서버
 a| 
DNS
 a| 
TCP/UDP 53
 a| 
필수입니다
 a| 
DNS 확인



 a| 
Keystone Collector(일반)
 a| 
고객 NTP 서버
 a| 
NTP
 a| 
UDP 123입니다
 a| 
필수입니다
 a| 
시간 동기화



 a| 
Keystone Collector(Keystone ONTAP용)
 a| 
Unified Manager를 참조하십시오
 a| 
MySQL
 a| 
TCP 3306
 a| 
옵션 기능
 a| 
Keystone 수집기에 대한 성능 메트릭 컬렉션



 a| 
Keystone Collector(일반)
 a| 
고객 모니터링 시스템
 a| 
HTTP
 a| 
TCP 777
 a| 
옵션 기능
 a| 
Keystone Collector 상태 보고



 a| 
고객의 운영 워크스테이션
 a| 
Keystone 컬렉터
 a| 
SSH를 클릭합니다
 a| 
TCP 22
 a| 
관리
 a| 
Keystone Collector 관리 액세스



 a| 
NetApp ONTAP 클러스터 및 노드 관리 주소
 a| 
Keystone 컬렉터
 a| 
HTTP_8000, ping
 a| 
TCP 8000, ICMP Echo Request/Reply
 a| 
옵션 기능
 a| 
ONTAP 펌웨어 업데이트를 위한 웹 서버입니다

|===


=== URL 액세스

Keystone 수집기는 다음 인터넷 호스트에 액세스해야 합니다.

|===


| 주소 | 이유 


 a| 
https://[]
 a| 
Keystone Collector 소프트웨어 업데이트 및 사용 보고



 a| 
https://[]
 a| 
청구 정보 및 AutoSupport 제공을 위한 NetApp HQ



 a| 
https://[]
https://[]
 a| 
Keystone Collector용 OS 업데이트(OVA 구축만 해당)



 a| 
https://[]
 a| 
MySQL 종속성 다운로드 및 업데이트(Linux 배포에만 해당)

|===