---
sidebar: sidebar 
permalink: release-notes/fixed-issues.html 
keywords: fixed issues 
summary: 다양한 Keystone STaaS 릴리즈에서 해결된 문제 
---
= 해결된 문제
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
이전 릴리스의 NetApp Keystone STaaS 서비스에서 발견된 문제는 이후 릴리스에서 해결되었습니다. 이러한 수정 사항이 있습니다.

[cols="3*"]
|===
| 문제 설명 | 수정 후 | 릴리스에서 수정되었습니다 


 a| 
계층화와 오브젝트 스토리지 모두에 대한 속도 계획을 적용할 수 있는 환경에서 MetroCluster와 FabricPool가 모두 설정된 경우 미러 볼륨(구성 볼륨과 FabricPool 볼륨 모두)에 대해 서비스 수준을 잘못 도출할 수 있습니다.
 a| 
미러 볼륨에 올바른 서비스 수준이 적용됩니다.
 a| 
2024년 2월 29일



 a| 
단일 서비스 수준 또는 요금 계획이 있는 일부 구독의 경우 * Volumes * 탭 보고서의 CSV 출력에 AQoS 준수 열이 누락되었습니다.
 a| 
준수 열은 보고서에 표시됩니다.
 a| 
2024년 2월 29일



 a| 
일부 MetroCluster 환경에서는 * 성능 * 탭의 IOPS 밀도 차트에서 이따금 이상 현상이 감지되었습니다. 이 문제는 볼륨을 서비스 수준에 부정확하게 매핑하기 때문에 발생합니다.
 a| 
차트가 올바르게 표시됩니다.
 a| 
2024년 2월 29일



 a| 
버스트 소비 기록에 대한 사용 표시기가 호박색으로 표시되었습니다.
 a| 
표시등이 빨간색으로 나타납니다.
 a| 
2023년 12월 13일



 a| 
Capacity Trend(용량 추세), Current Usage(현재 사용량) 및 Performance(성능) 탭의 날짜 범위 및 데이터는 UTC 표준 시간대로 변환되지 않았습니다.
 a| 
모든 탭의 쿼리 및 데이터에 대한 날짜 범위는 UTC 시간(서버 시간대)으로 표시됩니다. 또한 UTC 표준 시간대는 탭의 각 날짜 필드에 대해 표시됩니다.
 a| 
2023년 12월 13일



 a| 
탭과 다운로드한 CSV 보고서 간의 시작 날짜 및 종료 날짜가 일치하지 않습니다.
 a| 
고정.
 a| 
2023년 12월 13일

|===