---
sidebar: sidebar 
permalink: release-notes/fixed-issues.html 
keywords: fixed issues 
summary: 이전 릴리스의 NetApp Keystone STaaS 서비스에서 발견된 문제는 이후 릴리스에서 해결되었습니다. 
---
= 해결된 문제
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이전 릴리스의 NetApp Keystone STaaS 서비스에서 발견된 문제는 이후 릴리스에서 해결되었습니다.

[cols="3*"]
|===
| 문제 설명 | 수정 후 | 릴리스에서 수정되었습니다 


 a| 
Keystone 구독 * 페이지의 * 구독 * 탭에서 10-12개 이상의 구독을 선택할 경우 구독에 대한 보고서를 생성할 수 없습니다.
 a| 
고정
 a| 
2025년 01월 08일



 a| 
StorageGRID 구독에 대해 * 볼륨 및 개체 * 탭의 * 볼륨 요약 * 하위 탭이 로드되지 않습니다.
 a| 
고정
 a| 
2024년 11월 21일



 a| 
날짜 범위를 선택하는 * 시작 날짜 * 필드에는 * 소비 경향 * 탭으로 이동할 때 기본적으로 미래 날짜가 표시됩니다.
 a| 
고정
 a| 
2024년 09월 04일



 a| 
AQoS 정책을 설정할 때 Keystone Collector 관리 TUI가 응답하지 않습니다.
 a| 
고정
 a| 
2024년 08월 07일



 a| 
사용 차트는 * 용량 추세 * 탭의 * 용량 추세 * 옵션에서 현재 날짜에 해당하는 날짜를 이전 달의 시작 날짜와 종료 날짜로 선택한 경우 지정된 1일 기간 이후의 데이터를 표시합니다.
 a| 
이제 사용 차트에 지정된 1일 기간의 데이터가 올바르게 표시됩니다.
 a| 
2024년 6월 27일



 a| 
MetroCluster 구성으로 구성되지 않은 구독의 경우 * Capacity Trend * 탭 내의 * CVO 기본 * 및 * CVO 보조 * 서비스 수준에 대해 기록된 연속 버스트 데이터를 사용할 수 없습니다.
 a| 
고정
 a| 
2024년 6월 21일



 a| 
AutoSupport 구독에 대한 * 볼륨 세부 정보 * 탭에 나열된 객체 스토리지 사용 값이 잘못 표시됩니다.
 a| 
이제 객체 스토리지에 사용된 값이 올바르게 표시됩니다.
 a| 
2024년 6월 21일



 a| 
MetroCluster 구성으로 구성된 AutoSupport 구독의 경우 * Assets * 탭에서 클러스터 수준 정보를 볼 수 없습니다.
 a| 
고정
 a| 
2024년 6월 21일



 a| 
용량 추세 * 탭에서 생성된 CSV 보고서의 * 계정 이름 * 열에 쉼표가 있는 계정 이름이 포함된 경우 CSV 보고서에서 Keystone 데이터가 잘못 배치되었습니다 `(,)`.
 a| 
Keystone 데이터가 CSV 보고서에서 올바르게 정렬되어 있습니다.
 a| 
2024년 5월 29일



 a| 
소비량이 커밋된 용량보다 낮더라도 * Capacity Trend * 탭에서 누적된 버스트 사용량을 표시합니다.
 a| 
고정
 a| 
2024년 5월 29일



 a| 
Capacity Trend * 탭의 * Current Burst * 인덱스 아이콘에 대한 툴팁 텍스트가 올바르지 않습니다.
 a| 
올바른 도구 설명 텍스트 "_ 현재 사용 중인 버스트 용량입니다. 참고 이것은 선택한 날짜 범위가 아니라 현재 청구 기간에 적용됩니다. _"
 a| 
2024년 3월 28일



 a| 
AQoS 비준수 볼륨 및 MetroCluster 파트너에 대한 정보는 Keystone 데이터가 24시간 동안 존재하지 않는 경우 AutoSupport 구독에 사용할 수 없습니다.
 a| 
고정
 a| 
2024년 3월 28일



 a| 
한 서비스 수준에 대해서만 AQoS 준수를 충족하는 볼륨에 두 개의 서비스 수준이 할당된 경우 * 볼륨 요약 * 및 * 볼륨 세부 정보 * 탭에 나열된 AQoS 비준수 볼륨 수가 가끔 일치하지 않습니다.
 a| 
고정
 a| 
2024년 3월 28일



 a| 
AutoSupport 구독에 대한 * 자산 * 탭에는 정보가 없습니다.
 a| 
고정
 a| 
2024년 3월 14일



 a| 
계층화와 오브젝트 스토리지 모두에 대한 속도 계획을 적용할 수 있는 환경에서 MetroCluster와 FabricPool가 모두 설정된 경우 미러 볼륨(구성 볼륨과 FabricPool 볼륨 모두)에 대해 서비스 수준을 잘못 도출할 수 있습니다.
 a| 
미러 볼륨에 올바른 서비스 수준이 적용됩니다.
 a| 
2024년 2월 29일



 a| 
단일 서비스 수준 또는 요금 계획이 있는 일부 구독의 경우 * Volumes * 탭 보고서의 CSV 출력에 AQoS 준수 열이 누락되었습니다.
 a| 
준수 열은 보고서에 표시됩니다.
 a| 
2024년 2월 29일



 a| 
일부 MetroCluster 환경에서는 * 성능 * 탭의 IOPS 밀도 차트에서 이따금 이상 현상이 감지되었습니다. 이 문제는 볼륨을 서비스 수준에 부정확하게 매핑하기 때문에 발생합니다.
 a| 
차트가 올바르게 표시됩니다.
 a| 
2024년 2월 29일



 a| 
버스트 소비 기록에 대한 사용 표시기가 호박색으로 표시되었습니다.
 a| 
표시등이 빨간색으로 나타납니다.
 a| 
2023년 12월 13일



 a| 
Capacity Trend(용량 추세), Current Usage(현재 사용량) 및 Performance(성능) 탭의 날짜 범위 및 데이터는 UTC 표준 시간대로 변환되지 않았습니다.
 a| 
모든 탭의 쿼리 및 데이터에 대한 날짜 범위는 UTC 시간(서버 시간대)으로 표시됩니다. 또한 UTC 표준 시간대는 탭의 각 날짜 필드에 대해 표시됩니다.
 a| 
2023년 12월 13일



 a| 
탭과 다운로드한 CSV 보고서 간의 시작 날짜 및 종료 날짜가 일치하지 않습니다.
 a| 
고정.
 a| 
2023년 12월 13일

|===