---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: 'new features, release notes, enhancements, what"s new' 
summary: Keystone STaaS 새로운 기능 및 개선사항. 
---
= Keystone STaaS의 새로운 기능
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp은 모든 Keystone STaaS 서비스에서 새롭고 향상된 기능을 제공합니다.



== 2024년 5월 9일 새로운 기능 및 개선 사항

Active IQ 디지털 어드바이저(디지털 어드바이저)의 * Keystone 가입 * 화면에서 다음과 같은 기능이 향상되었습니다.



=== CSV 보고서의 새 열

이제 * Capacity Trend * 탭의 CSV 보고서에는 * Subscription Number * 및 * Account Name * 열이 포함되어 보다 자세한 내용을 확인할 수 있습니다.



=== 향상된 사용 유형 열

구독 * 탭 내의 * 사용 유형 * 열은 파일과 개체 모두에 대한 서비스 수준을 포함하는 구독에 대한 논리적 및 물리적 용도를 쉼표로 구분된 값으로 표시하도록 개선되었습니다.



=== 볼륨 세부 정보 탭에서 오브젝트 스토리지 세부 정보에 액세스합니다

볼륨 및 개체 * 탭의 * 볼륨 세부 정보 * 탭에는 이제 파일 및 개체 모두에 대한 서비스 수준을 포함하는 구독에 대한 볼륨 정보와 함께 개체 스토리지 세부 정보가 제공됩니다. Volume Details * 탭에서 * Object Storage Details * 버튼을 클릭하여 세부 정보를 볼 수 있습니다.



== 2024년 3월 28일 새로운 기능 및 개선 사항

Active IQ 디지털 어드바이저의 * Keystone 가입 * 화면에서 다음과 같은 기능이 향상되었습니다.



=== 볼륨 세부 정보 탭에 QoS 정책 규정 준수의 개선 사항이 표시됩니다

볼륨 및 개체 * 탭의 * 볼륨 세부 정보 * 탭은 이제 QoS(Quality of Service) 정책 준수에 대한 향상된 가시성을 제공합니다. 이전에 * AQoS * 로 알려진 열은 * Compliant * 로 이름이 변경되어 QoS 정책이 준수되고 있는지 여부를 나타냅니다. 또한 새 열 * QoS 정책 유형 * 이 추가되며, 이 열은 정책이 고정되었는지 또는 적응적인지를 지정합니다. 둘 다 해당되지 않으면 열에 _NOT AVAILABLE_이 표시됩니다. 자세한 내용은 을 참조하십시오 link:../integrations/volumes-objects-tab.html["볼륨 및 앰프, 개체 탭"^].



=== 볼륨 요약 탭에 새 열과 간소화된 구독이 표시됩니다

* 볼륨 및 개체 * 탭의 * 볼륨 요약 * 탭에는 * 보호 * 라는 새 열이 포함됩니다. 이 열에는 가입한 서비스 수준과 연결된 보호된 볼륨의 수가 표시됩니다. 보호된 볼륨 수를 클릭하면 * 볼륨 세부 정보 * 탭으로 이동하며, 여기서 필터링된 보호된 볼륨 목록을 볼 수 있습니다.
* 볼륨 요약 * 탭은 애드온 서비스를 제외한 기본 구독만 표시하도록 업데이트됩니다. 자세한 내용은 을 참조하십시오 link:../integrations/volumes-objects-tab.html["볼륨 및 앰프, 개체 탭"^].




=== Capacity Trend(용량 추세) 탭에서 누적된 버스트 상세 정보 표시를 변경합니다

Capacity Trend * 탭의 용량 사용 표시줄 차트 위로 마우스를 가져가면 나타나는 도구 설명에 현재 달의 누적 버스트에 대한 세부 정보가 표시됩니다. 이전 달에는 세부 정보를 사용할 수 없습니다.



=== Keystone 구독의 기록 데이터를 볼 수 있는 향상된 액세스

이제 Keystone 구독이 수정되거나 갱신된 경우 기간별 데이터를 볼 수 있습니다. 구독 시작 날짜를 이전 날짜로 설정하여 다음을 볼 수 있습니다.

* Capacity Trend * 탭의 소비 및 누적된 버스트 사용량 데이터,
* 성능 * 탭의 ONTAP 볼륨에 대한 성능 지표,


모두 선택한 구독 날짜를 기준으로 데이터를 표시합니다.



== 2024년 2월 29일부터 새로운 기능 및 개선 사항이 추가되었습니다

이 릴리즈의 Active IQ 디지털 어드바이저(디지털 어드바이저라고도 함) 대시보드 및 * Keystone 구독 * 화면에서 다음과 같은 몇 가지 향상이 이루어졌습니다.



=== [자산] 탭 추가

이제 * Keystone 구독 * 화면에 * 자산 * 탭이 포함됩니다. 이 새로운 탭은 구독에 따른 클러스터 레벨 정보를 제공합니다. 자세한 내용은 을 참조하십시오 link:../integrations/assets-tab.html["자산 탭"^].



=== 볼륨 및 개체 탭의 개선 사항

ONTAP 시스템 볼륨의 선명도를 높이기 위해 * 볼륨 요약 * 및 * 볼륨 세부 정보 * 라는 두 개의 새로운 탭 버튼이 * 볼륨 * 탭에 추가되었습니다. 볼륨 요약 * 탭은 가입한 서비스 수준과 연결된 볼륨의 전체 개수를 제공하며, 여기에는 AQoS 준수 상태 및 용량 정보가 포함됩니다. 볼륨 세부 정보 * 탭에는 모든 볼륨과 해당 세부 정보가 나열됩니다. 자세한 내용은 을 참조하십시오 link:../integrations/volumes-objects-tab.html["볼륨 및 앰프, 개체 탭"^].



=== Digital Advisor에서 향상된 검색 환경

이제 * Digital Advisor * 화면의 검색 매개 변수에 Keystone 구독 번호 및 Keystone 구독용으로 생성된 시청목록이 포함됩니다. 가입 번호 또는 시청자 목록 이름의 처음 세 문자를 입력할 수 있습니다. 자세한 내용은 을 참조하십시오 link:../integrations/keystone-aiq.html["Active IQ Digital Advisor에서 Keystone 대시보드를 확인할 수 있습니다"^].



=== 소비 데이터의 타임스탬프를 봅니다

Keystone 구독 * 위젯의 이전 대시보드에서 소비 데이터의 타임스탬프(UTC 기준)를 볼 수 있습니다.



== 2024년 2월 13일 새로운 기능 및 개선 사항

Active IQ 디지털 어드바이저(디지털 어드바이저라고도 함)의 * Keystone 가입 * 화면에서 다음과 같은 기능이 향상되었습니다.



=== 기본 구독에 연결된 구독을 볼 수 있습니다

일부 기본 구독에는 연결된 보조 구독이 있을 수 있습니다. 이 경우 * 구독 번호 * 열에 기본 구독 번호가 계속 표시되고, 연결된 구독 번호는 * 구독 * 탭의 새 열 * 링크된 구독 * 에 나열됩니다. 연결된 구독 * 열은 구독이 연결된 경우에만 사용할 수 있으며, 구독에 대해 알리는 정보 메시지를 볼 수 있습니다.



== 2024년 1월 11일 새로운 기능 및 개선 사항

이 릴리스의 새로운 기능에 대해 알아봅니다.

Active IQ 디지털 어드바이저(디지털 어드바이저)의 * Keystone 구독 * 화면에서 다음과 같은 기능이 향상되었습니다.



=== 누적된 연기에 대해 반환된 송장 데이터

이제 * Capacity Trend * 탭에서 * Accounted Burst * 의 레이블이 * Invoiced Accounting Burst * 로 수정됩니다. 이 옵션을 선택하면 청구된 누적 버스트 데이터의 월별 차트를 볼 수 있습니다. 자세한 내용은 을 참조하십시오 link:../integrations/aiq-keystone-details.html#view-invoiced-accrued-burst["송장 발행된 누적 버스트 보기"^].



=== 특정 요율계획에 대한 발생된 소비 상세 정보

rate plan이 _zero_committed capacity인 서브스크립션이 있는 경우 * Capacity Trend * 탭에서 계산된 소비 정보를 볼 수 있습니다. 송장 발행된 누적 소비 * 옵션을 선택하면 청구된 누적 소비 데이터에 대한 월별 차트를 볼 수 있습니다.



== 2023년 12월 15일 새로운 기능 및 개선사항

이 릴리스의 새로운 기능에 대해 알아봅니다.



=== 시청자 목록을 기준으로 검색하는 기능

Active IQ Digital Advisor(디지털 어드바이저)의 시청자 목록에 대한 지원이 Keystone 시스템으로 확장되었습니다. 이제 관심 목록을 사용하여 검색하여 여러 고객의 구독 세부 정보를 볼 수 있습니다. Keystone STaaS의 시청자 목록 사용에 대한 자세한 내용은 을 참조하십시오 link:../integrations/keystone-aiq.html#search-by-using-keystone-watchlists["Keystone 관심 목록을 사용하여 검색합니다"^].



=== UTC 시간대로 변환된 날짜

Active IQ 디지털 어드바이저의 * Keystone 구독 * 화면 탭에 반환된 데이터는 UTC 시간(서버 시간대)으로 표시됩니다. 쿼리에 날짜를 입력하면 UTC 시간으로 자동 간주됩니다. 자세한 내용은 을 참조하십시오 link:../integrations/aiq-keystone-details.html["Keystone 구독 대시보드 및 리포팅"^].
