---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: 'new features, release notes, enhancements, what"s new' 
summary: NetApp은 모든 Keystone STaaS 서비스에서 새롭고 향상된 기능을 제공합니다. 
---
= Keystone STaaS의 새로운 기능
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp은 모든 Keystone STaaS 서비스에서 새롭고 향상된 기능을 제공합니다.



== 2025년 06월 30일

이제 NetApp Keystone STaaS의 최신 릴리스인 Keystone 버전 3(v3)을 구독하실 수 있습니다. 이 버전은 간소화된 성능 서비스 수준, 추가 버스트 용량 옵션, 유연한 과금 주기 등 여러 가지 향상된 기능을 제공합니다. 이러한 개선 사항을 통해 스토리지 솔루션의 관리, 최적화 및 확장이 간소화됩니다. 자세한 내용은 을 link:../concepts/metrics.html["v3용 Keystone STaaS 서비스"]참조하십시오.



== 2025년 06월 19일



=== BlueXP의 Keystone 대시보드

이제 BlueXP에서 Keystone 대시보드에 바로 액세스할 수 있습니다. 이 통합을 통해 모든 Keystone 구독과 다른 NetApp 서비스를 한곳에서 모니터링, 관리 및 추적할 수 있습니다.

BlueXP의 Keystone 대시보드를 사용하면 다음을 수행할 수 있습니다.

* 모든 구독 세부 정보, 용량 사용량 및 자산을 한 곳에서 확인하세요.
* 필요에 따라 구독을 쉽게 관리하고 변경을 요청하세요.
* 귀하의 스토리지 환경에 대한 최신 정보를 받아보세요.


시작하려면 BlueXP 왼쪽 탐색 메뉴에서 *저장소 > 키스톤*으로 이동하세요. 자세한 내용은 을 link:../integrations/dashboard-overview.html["Keystone 대시보드 개요"]참조하십시오.



== 2025년 01월 08일



=== 매일 누적된 데이터 사용량 보기 옵션 추가

이제 송장 발행된 데이터를 표시하는 막대를 클릭하여 월별 또는 분기별 청구 기간에 대한 그래프 또는 표 형식으로 일별 누적 버스트 데이터 사용량을 볼 수 있습니다. 자세한 내용은 을 link:../integrations/consumption-tab.html#view-daily-accrued-burst-data-usage["매일 누적된 버스트 데이터 사용량을 봅니다"]참조하십시오.



== 2024년 12월 12일



=== 이름이 변경된 논리적 사용됨 열

볼륨 및 개체 * 의 * 볼륨 세부 정보 * 탭에 있는 * 논리적 사용된 * 열이 이제 * Keystone 논리적 사용됨 * 으로 이름이 바뀌었습니다.



=== Enhanced Assets(향상된 자산) 탭

Keystone 구독 * 화면의 * 자산 * 탭에는 * ONTAP * 및 * StorageGRID * 라는 두 개의 새로운 하위 탭이 있습니다. 이 하위 탭은 ONTAP에 대한 상세한 클러스터 레벨 통찰력과 구독 기반의 StorageGRID에 대한 그리드 레벨 정보를 제공합니다. 자세한 내용은 을 link:../integrations/assets-tab.html["자산 탭"^]참조하십시오.



=== 새 열 숨기기/표시 옵션

볼륨 및 개체 * 의 * 볼륨 세부 정보 * 탭에는 * 열 숨기기/표시 * 옵션이 포함되어 있습니다. 이 옵션을 사용하면 열을 선택하거나 선택 취소하여 원하는 대로 체적의 표 형식 목록을 사용자 지정할 수 있습니다. 자세한 내용은 을 link:../integrations/volumes-objects-tab.html["볼륨 및 앰프, 개체 탭"^]참조하십시오.



== 2024년 11월 21일



=== 송장 발행된 증액 버스트

이제 분기별 청구 기간을 선택한 경우 * 송장 누적된 버스트 * 옵션을 통해 분기별로 누적된 버스트 사용량 데이터를 볼 수 있습니다. 자세한 내용은 을 link:../integrations/consumption-tab.html#view-accrued-burst["송장 발행된 누적 버스트 보기"^]참조하십시오.



=== 볼륨 세부 정보 탭의 새 열

논리적 사용량 계산의 명확성을 높이기 위해 * Volumes & Objects * 탭의 * Volume Details * 탭에 두 개의 새 열이 추가되었습니다.

* * 논리적 AFS *: 볼륨의 활성 파일 시스템에서 사용하는 논리적 용량을 표시합니다.
* * 물리적 스냅샷 *: 스냅샷이 사용하는 물리적 공간을 표시합니다.


이 열은 볼륨의 활성 파일 시스템에서 사용하는 논리적 용량과 스냅숏에서 사용하는 물리적 공간을 모두 보여 주는 * Logical Used * 열을 보다 명확하게 보여 줍니다.



== 2024년 11월 11일



=== 향상된 보고서 생성

이제 Digital Advisor의 보고서 기능을 사용하여 Keystone 데이터의 세부 정보를 볼 수 있는 통합 보고서를 생성할 수 있습니다. 자세한 내용은 다음을 참조하세요. link:../integrations/options.html#generate-consolidated-report-from-digital-advisor["통합 보고서 생성"^] .



== 2024년 07월 10일



=== 라벨 수정

레이블 * Current Usage * 가 * Current Consumption * 로 변경되고 * Capacity Trend * 가 * Consumption Trend * 로 변경됩니다.



=== 구독 검색 표시줄

이제 * Keystone 구독 * 화면의 모든 탭에 있는 * 구독 * 드롭다운에 검색 표시줄이 포함됩니다. 구독 * 드롭다운에 나열된 특정 구독을 검색할 수 있습니다.



== 2024년 6월 27일



=== 일관된 구독 표시

Keystone 구독 * 화면이 업데이트되어 모든 탭에 선택된 구독 번호가 표시됩니다.

* Keystone 구독 * 화면 내의 탭을 새로 고치면 자동으로 * 구독 * 탭으로 이동하고 * 구독 * 드롭다운에 나열된 첫 번째 구독으로 모든 탭을 재설정합니다.
* 선택한 구독이 퍼포먼스 메트릭에 가입되어 있지 않은 경우 * Performance * 탭에는 탐색 시 * Subscription * 드롭다운에 나열된 첫 번째 구독이 표시됩니다.




== 2024년 5월 29일



=== 고급 버스트 표시기

사용 그래프 색인의 * 버스트 * 표시가 개선되어 버스트 한도 백분율 값이 표시됩니다. 이 값은 구독에 대해 합의된 버스트 제한에 따라 변경됩니다. 또한 * 사용 상태 * 열의 * 버스트 사용량 * 표시기 위로 마우스를 가져가면 * 구독 * 탭에서 버스트 한도 값을 볼 수 있습니다.



=== 서비스 수준 추가

서비스 수준 * CVO 기본 * 및 * CVO 보조 * 는 약정 용량이 없는 요금제 또는 Metro 클러스터로 구성된 요금제를 위한 Cloud Volumes ONTAP를 지원하기 위해 포함됩니다.

* Keystone 구독 * 위젯의 이전 대시보드와 * 용량 추세 * 탭의 * 에서 이러한 서비스 레벨에 대한 용량 사용 그래프를 볼 수 있으며, * 현재 사용량 * 탭에서 자세한 사용 정보를 확인할 수도 있습니다.
* 구독 * 탭에서 이러한 서비스 수준이 로 표시됩니다 `CVO (v2)` 사용 유형 * 열에서 이러한 서비스 수준에 따른 청구 여부를 확인할 수 있습니다.




=== 단기간 버스트를 위한 확대 기능

이제 * Capacity Trend * 탭에는 사용 차트에서 단기 폭주에 대한 세부 정보를 볼 수 있는 확대 기능이 포함되어 있습니다. 자세한 내용은 을 link:../integrations/consumption-tab.html["Capacity Trend(용량 추세) 탭"^]참조하십시오.



=== 향상된 구독 표시

기본 구독 표시는 추적 ID를 기준으로 정렬되도록 향상되었습니다. 이제 * 구독 * 드롭다운 및 CSV 보고서를 포함하여 * 구독 * 탭의 구독은 A, A, b, B 등의 순서에 따라 추적 ID의 알파벳 순서에 따라 표시됩니다.



=== 향상된 누적 버스트 디스플레이

이제 * Capacity Trend * 탭의 용량 사용 막대 차트 위로 마우스를 가져가면 나타나는 도구 설명에 커밋된 용량을 기준으로 누적된 버스트 유형이 표시됩니다. 약정 용량 요금제가 0인 구독의 경우 임시 소모 * 와 * 송장 발행된 소모 * 를 표시하고, 약정 용량이 0이 아닌 구독의 경우 * 임시 소모 * 및 * 송장 발행된 버스트 * 를 표시하여 임시 및 송장 발행된 버스트 * 를 구분합니다.



== 2024년 5월 9일



=== CSV 보고서의 새 열

이제 * Capacity Trend * 탭의 CSV 보고서에는 * Subscription Number * 및 * Account Name * 열이 포함되어 보다 자세한 내용을 확인할 수 있습니다.



=== 향상된 사용 유형 열

구독 * 탭 내의 * 사용 유형 * 열은 파일과 개체 모두에 대한 서비스 수준을 포함하는 구독에 대한 논리적 및 물리적 용도를 쉼표로 구분된 값으로 표시하도록 개선되었습니다.



=== 볼륨 세부 정보 탭에서 오브젝트 스토리지 세부 정보에 액세스합니다

볼륨 및 개체 * 탭의 * 볼륨 세부 정보 * 탭에는 이제 파일 및 개체 모두에 대한 서비스 수준을 포함하는 구독에 대한 볼륨 정보와 함께 개체 스토리지 세부 정보가 제공됩니다. Volume Details * 탭에서 * Object Storage Details * 버튼을 클릭하여 세부 정보를 볼 수 있습니다.



== 2024년 3월 28일



=== 볼륨 세부 정보 탭에 QoS 정책 규정 준수의 개선 사항이 표시됩니다

볼륨 및 개체 * 탭의 * 볼륨 세부 정보 * 탭은 이제 QoS(Quality of Service) 정책 준수에 대한 향상된 가시성을 제공합니다. 이전에 * AQoS * 로 알려진 열은 * Compliant * 로 이름이 변경되어 QoS 정책이 준수되고 있는지 여부를 나타냅니다. 또한 새 열 * QoS 정책 유형 * 이 추가되며, 이 열은 정책이 고정되었는지 또는 적응적인지를 지정합니다. 둘 다 해당되지 않으면 열에 _NOT AVAILABLE_이 표시됩니다. 자세한 내용은 을 참조하십시오 link:../integrations/volumes-objects-tab.html["볼륨 및 앰프, 개체 탭"^].



=== 볼륨 요약 탭에 새 열과 간소화된 구독이 표시됩니다

* 볼륨 및 개체 * 탭의 * 볼륨 요약 * 탭에는 * 보호 * 라는 새 열이 포함됩니다. 이 열에는 가입한 서비스 수준과 연결된 보호된 볼륨의 수가 표시됩니다. 보호된 볼륨 수를 클릭하면 * 볼륨 세부 정보 * 탭으로 이동하며, 여기서 필터링된 보호된 볼륨 목록을 볼 수 있습니다.
* 볼륨 요약 * 탭은 애드온 서비스를 제외한 기본 구독만 표시하도록 업데이트됩니다. 자세한 내용은 을 참조하십시오 link:../integrations/volumes-objects-tab.html["볼륨 및 앰프, 개체 탭"^].




=== Capacity Trend(용량 추세) 탭에서 누적된 버스트 상세 정보 표시를 변경합니다

Capacity Trend * 탭의 용량 사용 표시줄 차트 위로 마우스를 가져가면 나타나는 도구 설명에 현재 달의 누적 버스트에 대한 세부 정보가 표시됩니다. 이전 달에는 세부 정보를 사용할 수 없습니다.



=== Keystone 구독의 기록 데이터를 볼 수 있는 향상된 액세스

이제 Keystone 구독이 수정되거나 갱신된 경우 기간별 데이터를 볼 수 있습니다. 구독 시작 날짜를 이전 날짜로 설정하여 다음을 볼 수 있습니다.

* *용량 추세* 탭에서 소비량 및 누적 버스트 사용 데이터를 확인할 수 있습니다.
* *성능* 탭에서 ONTAP 볼륨의 성능 측정 항목을 볼 수 있습니다.


데이터는 선택한 구독 시작 날짜를 기준으로 표시됩니다.



== 2024년 2월 29일



=== [자산] 탭 추가

이제 * Keystone 구독 * 화면에 * 자산 * 탭이 포함됩니다. 이 새로운 탭은 구독에 따른 클러스터 레벨 정보를 제공합니다. 자세한 내용은 을 참조하십시오 link:../integrations/assets-tab.html["자산 탭"^].



=== 볼륨 및 개체 탭의 개선 사항

ONTAP 시스템 볼륨의 선명도를 높이기 위해 * 볼륨 요약 * 및 * 볼륨 세부 정보 * 라는 두 개의 새로운 탭 버튼이 * 볼륨 * 탭에 추가되었습니다. 볼륨 요약 * 탭은 가입한 서비스 수준과 연결된 볼륨의 전체 개수를 제공하며, 여기에는 AQoS 준수 상태 및 용량 정보가 포함됩니다. 볼륨 세부 정보 * 탭에는 모든 볼륨과 해당 세부 정보가 나열됩니다. 자세한 내용은 을 참조하십시오 link:../integrations/volumes-objects-tab.html["볼륨 및 앰프, 개체 탭"^].



=== Digital Advisor에서 향상된 검색 환경

이제 * Digital Advisor * 화면의 검색 매개 변수에 Keystone 구독 번호 및 Keystone 구독용으로 생성된 시청목록이 포함됩니다. 가입 번호 또는 시청자 목록 이름의 처음 세 문자를 입력할 수 있습니다. 자세한 내용은 을 link:../integrations/keystone-aiq.html["Active IQ Digital Advisor에서 Keystone 대시보드 보기"^]참조하십시오.



=== 소비 데이터의 타임스탬프를 봅니다

Keystone 구독 * 위젯의 이전 대시보드에서 소비 데이터의 타임스탬프(UTC 기준)를 볼 수 있습니다.



== 2024년 2월 13일



=== 기본 구독에 연결된 구독을 볼 수 있습니다

일부 기본 구독에는 연결된 보조 구독이 있을 수 있습니다. 이 경우 * 구독 번호 * 열에 기본 구독 번호가 계속 표시되고, 연결된 구독 번호는 * 구독 * 탭의 새 열 * 링크된 구독 * 에 나열됩니다. 연결된 구독 * 열은 구독이 연결된 경우에만 사용할 수 있으며, 구독에 대해 알리는 정보 메시지를 볼 수 있습니다.



== 2024년 1월 11일



=== 누적된 연기에 대해 반환된 송장 데이터

이제 * Capacity Trend * 탭에서 * Accounted Burst * 의 레이블이 * Invoiced Accounting Burst * 로 수정됩니다. 이 옵션을 선택하면 청구된 누적 버스트 데이터의 월별 차트를 볼 수 있습니다. 자세한 내용은 을 link:../integrations/consumption-tab.html#view-accrued-burst["송장 발행된 누적 버스트 보기"^]참조하십시오.



=== 특정 요율계획에 대한 발생된 소비 상세 정보

rate plan이 _zero_committed capacity인 서브스크립션이 있는 경우 * Capacity Trend * 탭에서 계산된 소비 정보를 볼 수 있습니다. 송장 발행된 누적 소비 * 옵션을 선택하면 청구된 누적 소비 데이터에 대한 월별 차트를 볼 수 있습니다.



== 2023년 12월 15일



=== 시청자 목록을 기준으로 검색하는 기능

Digital Advisor의 감시 목록에 대한 지원이 Keystone 시스템까지 확장되었습니다. 이제 관심 목록을 사용하여 검색하여 여러 고객의 구독 세부 정보를 볼 수 있습니다. Keystone STaaS의 시청자 목록 사용에 대한 자세한 내용은 을 참조하십시오 link:../integrations/keystone-aiq.html#search-by-keystone-watchlists["Keystone 관심 목록으로 검색합니다"^].



=== UTC 시간대로 변환된 날짜

Digital Advisor의 *Keystone 구독* 화면 탭에 반환된 데이터는 UTC 시간(서버 시간대)으로 표시됩니다. 쿼리에 날짜를 입력하면 UTC 시간으로 자동 간주됩니다. 자세한 내용은 을 link:../integrations/keystone-aiq.html["Keystone 구독 대시보드 및 리포팅"^]참조하십시오.
