---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: 'new features, release notes, enhancements, what"s new' 
summary: Keystone STaaS 새로운 기능 및 개선사항. 
---
= Keystone STaaS의 새로운 기능
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp은 모든 Keystone STaaS 서비스에서 새롭고 향상된 기능을 제공합니다.



== 2024년 1월 11일 새로운 기능 및 개선 사항

이 릴리스의 새로운 기능에 대해 알아봅니다.

Active IQ 디지털 어드바이저(디지털 어드바이저)의 * Keystone 구독 * 화면에서 다음과 같은 변경 사항이 적용되었습니다.



=== 누적된 연기에 대해 반환된 송장 데이터

이제 * Capacity Trend * 탭에서 * Accounted Burst * 의 레이블이 * Invoiced Accounting Burst * 로 수정됩니다. 이 옵션을 선택하면 청구된 누적 버스트 데이터의 월별 차트를 볼 수 있습니다. 자세한 내용은 을 참조하십시오 link:../integrations/aiq-keystone-details.html#view-invoiced-accrued-burst["송장 발행된 누적 버스트 보기"^].



=== 특정 요율계획에 대한 발생된 소비 상세 정보

rate plan이 _zero_committed capacity인 서브스크립션이 있는 경우 * Capacity Trend * 탭에서 계산된 소비 정보를 볼 수 있습니다. 송장 발행된 누적 소비 * 옵션을 선택하면 청구된 누적 소비 데이터에 대한 월별 차트를 볼 수 있습니다.



== 2023년 12월 15일 새로운 기능 및 개선사항

이 릴리스의 새로운 기능에 대해 알아봅니다.



=== 시청자 목록을 기준으로 검색하는 기능

Active IQ Digital Advisor(디지털 어드바이저)의 시청자 목록에 대한 지원이 Keystone 시스템으로 확장되었습니다. 이제 관심 목록을 사용하여 검색하여 여러 고객의 구독 세부 정보를 볼 수 있습니다. Keystone STaaS의 시청자 목록 사용에 대한 자세한 내용은 을 참조하십시오 link:../integrations/keystone-aiq.html#search-by-using-keystone-watchlists["Keystone 관심 목록을 사용하여 검색합니다"^].



=== UTC 시간대로 변환된 날짜

Active IQ 디지털 어드바이저의 * Keystone 구독 * 화면 탭에 반환된 데이터는 UTC 시간(서버 시간대)으로 표시됩니다. 쿼리에 날짜를 입력하면 UTC 시간으로 자동 간주됩니다. 자세한 내용은 을 참조하십시오 link:../integrations/aiq-keystone-details.html["Keystone 구독 대시보드 및 리포팅"^].
